M7R0
I.SolveVectoLib=6"%&falseGE\[ldq%)MySolve0Gt+6$%%eqnsG%%varsG6%%'resultG%'nghie
mG%*tapnghiemGF$F$C&>8$<">8&<#-%&solveG6$9$9%?&8%F5%%trueG>F2-%&unionG6$F2<#F=O
F2F$F$F$6#""#%,ReadCObjectGf*6#'%)fileNameG%'stringG69%+objectNameG%+baseObject
G%*variablesG%,constraintsG%3constructRelationsG%+propertiesG%5computationRelat
ionsG%&rulesG%*functionsGF-%%lineG%#fdG%"kG%%InitG%/readObjectNameG%/readBaseOb
jectG%.readVariablesG%/readContraintsG%7readConstructRelationsG%/readProperties
G%9readComputationRelationsG%.readFunctionsG%+readRulesOGF$F$C5>81f*F$F$F$F$C+>
T#Q!F$>T%7$7"Fio>T'Fho>T)Fio>T+Fio>T-Fio>T/Fio>T1Fio>T3FioF$F$64FNF2FOF=FPF5FQ8
'FR8(FS8)FT8*FU8+FV8,>82f*F$F$F$F$C$>Fdo-%+SearchTextG6$Q":F$Fgo>F[p-%(convertG
6$-%&parseG6#-%*substringG6$Fgo;,&Fdo"""FdrFdr-%'lengthG6#FgoFLF$F$6(FY80FW8.FN
F2>83f*F$6$%%tempG%"iGF$F$?(F$FdrFdrF$30Fdo""!/-Feq6$Q0begin_variablesF$FdoFdsC
$@$0FdoFeoC&>Fgo-Feq6$FgqFdo>F27#-F]r6#-F`r6$Fdo;Fdr,&FgoFdr!""Fdr?(F=FdrFdr-%%
nopsG6#F2F>>&F[p6#FF7$-%#opG6#F^u-Fjq6$-F]r6#-F`r6$Fdo;,&FgoFdrFdrFdr-Ffr6#FdoF
L>&F[p6#Fdr7$-Fbu6#F_v-FbuF\u>Fdo-I)readlineG6$%*protectedG%(_syslibG6#F]pF$F$6
*FWFjrFYFirFOF=FX8/>84f*F$F^sF$F$C$>Fdo-FgvFgr?(F$FdrFdrF$3Fcs/-Feq6$Q.end_vari
ablesF$FdoFdsC$@$F[tC&>F[pF^t>F27#-F]r6#-F`r6$Fdo;Fdr,&F[pFdrFhtFdr?(F=FdrFdrFj
tF>>&F]pF_u7$-Fbu6#Fhx-Fjq6$-F]r6#-F`r6$Fdo;,&F[pFdrFdrFdrF\vFL>&F]pF`v7$-Fbu6#
FeyFdv>FdoFcwF$F$6*FWFjrFXF]wFYFirFPF5>85f*F$F$F$F$C$>FdoFcw?(F$FdrFdrF$3Fcs/-F
eq6$Q0end_constraintsF$FdoFdsC$@$F[t>F[p7$-Fbu6#F[p-F]rF]v>FdoFcwF$F$6(FWFjrFXF
]wFQFip>86f*F$F$F$F$C$>FdoFcw?(F$FdrFdrF$3Fcs/-Feq6$Q8end_construct_relationsF$
FdoFdsC$@$F[t>F[pFiz>FdoFcwF$F$6(FWFjrFXF]wFRFjp>87f*F$F$F$F$C$>FdoFcw?(F$FdrFd
rF$3Fcs/-Feq6$Q/end_propertiesF$FdoFdsC$@$F[t>F[pFiz>FdoFcwF$F$6(FWFjrFXF]wFSF[
q>88f*F$6%%%exprG%"fG%-readRelationGF$F$C&>F5f*F$F$F$F$C&>Fdo7#Fgo>Fgo-FgvF[[l?
(F$FdrFdrF$30FgoFds/-Feq6$Q-end_relationF$FgoFdsC$@$0FgoFeoC$>F]p-%$rhsG6#-F]rF
gr>Fdo7$-FbuF]vF]p>FgoF]^l>&Fdo6#""'-F]r6#Fc_lF$F$6*Fd]lF=FWFdoFXFgoFc]lF2>F=Fi
o>FdoFcw?(F$FdrFdrF$3Fcs/-Feq6$Q:end_computation_relationsF$FdoFdsC$@$2Fds-Feq6
$Q/begin_relationF$FdoC$-F5F$>F[p7$FjzF=>FdoFcwF$F$6(FWFjrFXF]wFTF\q>8:f*F$61%*
readRule1G%-readKindRuleGFZ%/readHypothesisG%)readGoalG%)readProcGFgn%)kindRule
G%.variableNamesG%/variableNames1G%.variableTypesG%/hypothesisGoalG%&procsGFYF`
sF$F$C+>F5f*F$F$F$F$C'>FdoFeo>FgoFio>F[pFio>F]p7$F3F3>F_pFeoF$F$6,FfalF]qFgalF^
qFialFjrFjalF]wF[blFir>F=f*F$F$F$F$>FdoFj^lF$F$6&FfalF]qFWFdo>Fipf*F$F$F$F$C$>F
doFcw?(F$FdrFdrF$3Fcs/-Feq6$Q4end_hypothesis_partF$FdoFdsC$>F_vF\[l>FdoFcwF$F$6
(FWFdoFXFgoFjalF]w>Fjpf*F$F$F$F$C$>FdoFcw?(F$FdrFdrF$3Fcs/-Feq6$Q.end_goal_part
F$FdoFdsC$>F^uF\[l>FdoFcwF$F$Fhcl>F[qf*F$F$F$F$C$>FdoFdq>F[pF\rF$F$6(FYF`oFWFdo
F[blFir>F\qf*F$F$F$F$C&>FdoFdq>F[p7#-F]r6#-F`r6$Fgo;Fdr,&FdoFdrFhtFdr?(F]pFdrFd
r-F[uF[[lF>>F_p7$-Fbu6#F_pFiq>Fap7$-Fbu6#FapFjzF$F$6.FYF`oFWFdoFhal8-F`sF`qFial
FjrFgalF^q>F2f*F$F$F$F$C(-FdoF$>FgoF]^l?(F$FdrFdrF$3F`^l/-Feq6$Q+begin_ruleF$Fg
oFdsC$>FgoF]^l@$2Fds-Feq6$Q*end_rulesF$FgoOF$>FgoF]^l?(F$FdrFdrF$3F`^l/-Feq6$Q)
end_ruleF$FgoFdsC$@+2Fds-Feq6$Q*kind_ruleF$Fgo-F]pF$2Fds-Feq6$Q0hypothesis_part
F$Fgo-F_pF$2Fds-Feq6$Q*goal_partF$Fgo-FapF$2Fds-Feq6$Q&proc:F$Fgo-FcpF$@$Fg^l-F
epF$>FgoF]^l>Fgp7$-Fbu6#Fgp7'T5T7T9T;T=F$F$6>FZF5FWFdoFXFgoFbalF=FcalFipFdalFjp
FealF[qFgnF\qFUF[pFfalF]qFgalF^qFialFjrFjalF]wF[blFir>FdoFcw?(F$FdrFdrF$3Fcs/-F
eq6$FeglFdoFds-F2F$F$F$6(FWFjrFXF]wFUF]q>89f*F$F$F$F$C$>FdoFcw?(F$FdrFdrF$3Fcs/
-Feq6$Q.end_functionsF$FdoFdsC$@$F[t>F[pFiz>FdoFcwF$F$6(FWFjrFXF]wFVF^q-F`oF$>F
cflFio>F]w-I&fopenG6$FivFjv6%F:%%READGI%TEXTG6$FivFjv>Fjr-Fgv6#F]w?(F$FdrFdrF$3
0FjrFds/-Feq6$Q-begin_objectF$FjrFds>FjrFe\m?(F$FdrFdrF$3Fi\m/-Feq6$Q+end_objec
tF$FjrFdsC$@22FdsF[]mC&-F`qF$>FjrFe\m-F\sF$\2Fds-Feq6$FhsFjr-F_wF$2Fds-Feq6$Q2b
egin_constraintsF$Fjr-F\zF$2Fds-Feq6$Q:begin_construct_relationsF$Fjr-F`[lF$2Fd
s-Feq6$Q1begin_propertiesF$Fjr-F`\lF$2Fds-Feq6$Q0begin_functionsF$Fjr-F[[mF$2Fd
s-Feq6$Q<begin_computation_relationsF$Fjr-F`]lF$2Fds-Feq6$Q,begin_rulesF$Fjr-F^
alF$>FjrFe\m-I'fcloseG6$FivFjvFf\m>Fcfl7+F2F=F5FipFjpF[qF\qF]qF^qOFcflF$F$F$%.I
ndex_ElementGt+6$%#elG%$expG6$F`s%#kqGF$F$C%>F=F3?(F2FdrFdr-F[u6#F;F>@$/F:-Fbu6
$F2F;>F=-FA6$F=<#F2@'/F=F3OFds/-F[u6#F=FdrO-FbuF_bmOF=F$F$F$6#FF%)IsVecto0Gt+6#
%"aGF$F$F$C$@$/F:FdsOF>@%5/F:&%&VectoG6#Fds/-Fbu6$FdrF:-Fbu6$FFF:OF>OF%F$F$F$6#
Fdr%0Intersect_UnifyGt+6$%%AsetG%%BsetG6$%%factG%%CsetGF$F$C%>F=F3?&F2F:F>@$-%*
Unify_In1GFeam>F=<$FabmF2OF=F$F$F$6#FF%)MyFactorGt+6#Fc]l6.%&expr1GF`s%"jGF_s%&
temp2GF\am%$solG%%flagG%%numsG%&daxetG%&checkG%&temp3GF$F$C+>F2-Fjq6$F:%%listG>
F^qFjt>F\q7#7%7$7#FeoFcfm7#-Fjq6$F:FLF:>F]qF>>FcflFio>%(daxetRGGFio?(F$FdrFdrF$
/F]qF>C*>F]qF%>F[qFio>F]w&&F\q6#-F[u6#F\q6#""$>F2F]w>F2-Fjq6$F2F]fm>F^qFjt?(F=F
drFdrF^qF>C&@$/-%'memberG6$&F2F_bmFcflF>F\^m>FjrF%?(F5,&F=FdrFdrFdrFdrF^qF>C&@$
/-Fbhm6$&F26#F5FcflF>F\^m>Fip-%'factorG6#,&FdhmFdrF]imFdr@$/-Fbhm6$FipFjfmF>F\^
m@$-%%typeG6$Fip%"*GC$>Fjp-%+CongBTNhanG6#Fip@$0FjpFipC(>F[q7$-Fbu6#F[qFip>F]qF
>>Fjfm7$-Fbu6#FjfmFip>Fcfl7$-Fbu6#FcflF]im>FjrF>[@$/FjrF%>F[q7$FgjmFdhm@$F\gmC$
>F[q-Fjq6$F[q%"+G>F\q7%-FbuFegm7%Fbfm7#-Fjq6$F[qFLF[q7%Fbfm7#-Fjq6$-F`jmFhjmFLF
i\n@$/FdgmFdrOFioOF\qF$F][nF$6#Fdr%-SolveVecto_1Gt+6#'%%goalG%"=G63%#VTG%#VPG%'
varsVTG%'varsVPG%)varsTempG%'pointsG%"vGF_sF`sF`dmFd]l%%fSetG%&fSet0G%*applyRul
eG%&temp1G%)diemChenGFc]lF$F$C8>F2-%$lhsG6#F:>F=-F[_lFf^n>%(FactSetG%&HyposG>%)
FactSet0GF3>%*FactSetObGF3>FdemF>>%$SolGFio>%&TestRGFio>F]q/&-%*CongVectoG6#,&F
2FdrF=FhtF`vF_cm>Fb_n7$-Fbu6#Fb_n7%Fbfm&Fh_nF_uFg_n@$Ff_nC$>FdemF%OFb_n@$0F]qF:
C$>F2-Fe^n6#F]q>F=F_cm?(F$FdrFdrF$/FdemF>-%2Deduce_RulesVectoGF$?&F^q%(ObjectsG
F>@$0-%)NameTypeG6#F^qQ"?F$>F__n-FA6$F__n-%,GetFactsObjGFgan>F]w-%&minusG6$Fj^n
F[_n>F]w7%-FbuFf\m-Fbu6#F__n-Fbu6#F]_n>FdemF>>%&chisoGFds?(F$FdrFdrF$F^anC%>F[c
n,&F[cnFdrFdrFdr>FdemF%?&FjrF]wF>?&F^q&FjrF_uF>C&@$-Fbhm6$7$-Fbu6#&FjrF`vF^qFd_
nF\^m>F]q-%'MySubsG6$F^qF2>F`q&-Fi_nF[anF`v@$/-%,Lap_LoiGiaiG6$F2F`qF%C'>FdemF>
>F2Fadn>Fb_n7$F^`n7%7$7#Ficn7#F^q&FbdnF_uF2>Fd_n<$-Fbu6#Fd_nFhcn@$5/-FdbmF\uF>/
F2FdsOFb_n>F]q7#&&Fb_n6#-F[uF_`nFfgm>Fb_n7%Q6GoiY_Debai_TuongDuongF$/&-Fi_n6#,&
Fd^nFdrFh^nFhtF`vFds/F]qFdsOFb_nF$6)FdemFj^nF]_nF__nFb_nF[cnFd_nF$6#Fdr%1readFu
nctionsTXTGf*FI6+FWFX%(returnzG%)funcnameG%*argumentsGFSF`sFY%'VitrikGF$F$C/>%+
Func_NamesGFio>F5Feo>FipFeo>FjpFio>F[qFeo>F=F]\m>F2-FgvF_bm?(F$FdrFdrF$30F2Fds/
-Feq6$Fc_mF2Fds>F2F^hn>F2F^hn>F^qf*6#FW6&FY%"sG%"nGF`sF$F$C&>F5-FfrFf^n>FipFdr?
(F$FdrFdrF$1FipF5C$>F=-F`r6$F:Fip@%-%&evalbG6#/F=Q"~F$>Fip,&FipFdrFdrFdrFc[nOFi
pF$F$F$?(F$FdrFdrF$3Fahn/-Feq6$Fd[mF2FdsC$@$0F2FeoC)>F\q-F^qF\u>F]q,(F\qFdr!"#F
dr-Feq6%F\jnF2;F\q-FfrF\uFdr>F5-F`r6$F2;F\qF]q>Fip-Fjq6$-F]r6#-F`r6$F2;,&F]qFdr
FFFdr,&-Feq6$Q"(F$F2FdrFhtFdrFL>Fjp-%$mapG6$f*6#F[inF$6$%)operatorG%&arrowGF$Fe
fmF$F$F$7#-F]r6#-F`r6$F2;,&F`\oFdrFdrFdr,&-Feq6$Q")F$F2FdrFhtFdr>F[q-F]r6#-F`r6
$F2;-Feq6$Q"|frF$F2Fa[o>Fggn7$-Fbu6#Fggn7&F5FipFjpF[q>F2F^hn-Fa`mF_bmOFggnF$Fc^
oF$%2ObjStruct_ReplaceGt+6#%"dG6&%'OSTempGF`sFY%(thaytheGF$F$C(>F2-%*ObjStructG
6#-%*type_OnetGFf^n>F2-%%subsG6%/Q'ObjectF$F:-%$seqG6$/&&&F2FfgmF`vF_bm-%".G6$F
:F``o/F=;Fdr-F[u6#Fa`oF2>FipF3@%-Fjim6$F:%(indexedGC&>F2-Fh_o6$-F]`o6$/&7#-Fbu6
#-F]r6#&F2F`vF_bm&7#-FbuFf^nF_bm/F=;Fdr-F[u6#F^boF2>&Fb`oF_u-Fe\o6$f*Fh\oF$Fi\o
F$-Fjq6$-Fh_o6$-F]`o6$/&7#-Fbu6#-F]rFcvFgr&7#-Fbu6#T$Fgr/Fgo;Fdr-F[u6#Ffco-F]rF
f^nFLF$F$6(F[_oF:F`sF=F]_oF2Febo>F\bo-Fjq6$-Fh_o6$FcaoFjaoFL?(F5FdrFdrFh`oF>@$2
Fds-Feq6$Q$GocF$-Fjq6$&Fa`oF^imFL>Fip<$-FbuFajm/F]eo-Fd`o6$F:-F]r6#-%$catG6$Fjd
o&-Fbu6#-F]r6#&FeboF^imF_u?&F=&%+Fact_KindsGF`vF>@$3/&F=F`vF:-Fjim6$-F]r6#&F=F_
uF^aoC&>F2-Fh_o6$-F]`o6$/&Fgao6#Faem&7#-Fbu6#FhfoFcgo/Faem;Fdr-F[u6#FegoF2>Febo
-Fe\o6$f*Fh\oF$Fi\oF$-Fjq6$-Fh_o6$-F]`o6$/&7#-Fbu6#-F]r6#&FgoF`vFcgo&7#-Fbu6#-F
]r6#&FdoF_uFcgo/Faem;Fdr-F[u6#F_ioF^doFLF$F$6&F`sF=F]_oF2Febo>F\bo-Fjq6$-Fh_o6$
F_goFjaoFL?(F5FdrFdrFh`oF>@$Fgdo>FipF_eo>F2-Fh_o6$FipF2OF2F$F$F$6#FdrFfdnt+6$%#
KqG%)KqKeTiepG6%%6KqKeTiep_VectoDoi_SetG%'Kq_SetG%-KqKeTiep_SetGF$F$C'>F=-%)Set
_VarsGFf^n>F5-Fb[pFaam>F2-Fe\o6$f*Fh\oF$Fi\oF$-%)VectodoiGFf^nF$F$F$F5@$5-%'sub
setG6$F=F5-F^\p6$F=F2OF>OF%F$F$F$6#FF%.readOperatorsGf*FI6%FXFW%'chuyenGF$F$C+>
F5f*6#'F[inF]fm6%F\inF`s%"lGF$F$C'>F2-F[uFf^n>F=Fdr>F5Fio?(F$FdrFdrF$1F=F2C$@%-
Fjim6$-Fbu6$F=F:F]fm>F57$-FbuF^im-Fe\o6$f*6#%"xGF$Fi\oF$FefmF$F$F$&F:F_bm>F57$F
_^p-Fjq6$Fe^pFL>F=FghmOF5F$F$F$>%)Op_NamesGFio>F2F]\m>F=-FgvF\u?(F$FdrFdrF$30F=
Fds/-Feq6$Q0begin_OperatorsF$F=Fds>F=F`_p>F=F`_p?(F$FdrFdrF$3Fc_p/-Feq6$Q.end_O
peratorsF$F=FdsC$@$0F=Feo>F]_p7$-Fbu6#F]_p-F56#-F]rF_bm>F=F`_p-Fa`mF\uOF]_pF$Ff
`pF$%-SolveVecto_5Gt+6#Fc]n64Ff]nFg]n%+ApplyRulesGF_sFc]lFa^n%%Set1G%%Set2GFgem
FhemF`s%%thayG%-thayVectoDoiGFbem%+LayBTVectoG%+listVtChenG%&temp4G%(BtdaXetGF$
F$CA>F2Fd^n>F=Fh^n>Fj^nF[_n>F]_nF3>F__nF3>FdemF>>Fd_nF3>F^qF3>F]w7&%"uGF\^n%"gG
%"mG>Fb_nFio>F\zFio>F`qt+F^em6%%#dsGFeemF`sF$F$C&>F2F[fm>F=Fjt?(F5FdrFdrF=F>@$/
-%$hasG6$F]imF`cmF%>F]imFdsO-Fjq6$F2F]\nF$F$F$6#Fdr>F5t+F^em6)Fd]lF`s%&tempAG%'
tempA1G%#VtG%#cfG%&flag2GF$F$C%>FjpF:>F\qF>?(F$FdrFdrF$/F\qF>C%>F[cnF_cn>F\qF%?
&F2F]^nF>?&F=&F2F_uF>C&@$-Fbhm6$F=Fd_nF\^m>F5-Fdo6#-F^dn6$F=Fjp@$/-Fbhm6$F5FgoF
>F\^m@$/-Ffdn6$FjpF5F%C+@%5-Fjim6$-Fbu6$FdrF\bo%'symbolG-Fjim6$Fefp%(complexG>F
[qFeo>F[q-FbuF[bo>F\qF>>FdemF>>Fip-Fh_o6$F[pF5>Fjp-Fh_o6$F]pF5>Fgo7$-FbuFgrFjp>
Fb_n7$F^`n7%7$7#Fgjm7#F=7#-Fjq6$/F_p-Fh_o6$F[pFipFLFjp>Fd_n<$FdenF=OFb_nF$F$6,F
eapFirFiapF\zFcapF]qFbapF\qFf]nF26#Fdr>Firt+F^em6$%(set_varG%%settGF$F$C'>F=Fio
>F2Fa[p?&FdoF2F>@$-Fbhm6$-Fj[pF]vFgo>F=7$Fabm/Fdo,$FfipFht@$2FdsF^bmO-Fh_oF\^pO
F:F$F$6&F`sFjrFg]nF=6#Fdr>F\qFio>F]qFio>F^qFio?(FjrFdrFdrF^bmF>C%>F\q7$F`\n/&F=
6#Fjr&F]wF[[q>F]q7$-FbuF[an/F\[qFjjp>F^q<$F\[q-FbuFgan?(F$FdrFdrF$F^anF_an?&Fjr
FbanF>@$0-FfanF[[qFhan>F__n-FA6$F__n-F]bnF[[q>F]^nF_bn>F]^n7%-Fbu6#F]^nFebnFgbn
>F]^n-%(XepLuatG6$F:F]^n>Fb_n7#7%Fbfm7#-Fjq6$/F2F2FLF2>FdemF>>FjpF2>F[cnFds?(F$
FdrFdrF$F^anC*>FdemF%>FjpF^fn-F56#Fjp>FjpF^fn@$/-Feq6$Q&VectoF$-Fjq6$FjpFLFdsOF
b_n>F`o-Fh_o6$F]qFjp>F\s-F`bn6$-Fb[pF_bm-Fb[p6#F`o@$2Fds-F[u6#F\sC%>Fip-F`qFe]q
>F[q-%)DiemChenG6#/Fip-Fjq6$F\sF]\n@$2Fds-F[uFhjmC+>FdemF>>Fcfl-%+ChenDiemBTG6$
/FipF\sF[q>F_w-FirFa[n>Fcfl-Fh_o6$/FipFcflF`o>F_w-Fh_o6$/FipF_wF`o>Fjp-Fh_o6$F
\qF_w>F_w-Fjq6$/F2F_wFL>Fb_n7$F^`n7%Fbfm7$-Fjq6$/F2FcflFLF_wFjp@$Fh]qOFb_n>Fcfl
-Fh_o6$F]qF^fn>Fb_nF]fn>Fb_n7%FdfnFgaqFgaqF$6*FdemFj^nF]_nF__nFb_nF[cnFd_nF]^nF
$6#Fdr%*Rule_TypeGt+6#FU60F`sFaemFY%%ruleG%+r_varNamesG%+r_varTypesG%(r_hyposG%
$objG%#vtGF_s%'r_hypoGF\am%$kq1GFeemF$F$C'@$/-I)whattypeG6$FivFjvFf^nFgfpOFio?(
F2FdrFdrFb]pF>C,>Fip-Fbu6$F2F:>Fjp&FipF_u>F[q&FipFfgm>F\q&&Fip6#""%F`v@$/F\qF3C
$>&F]wF\uFioF\^m>F=Fdr?(F$FdrFdrF$2FdsFdgmC'>Fjr-Fbu6$FdrF\q>F\q-F`bn6$F\q<#Fjr
@%/-Fjim6$FjrF]fmF%>FjrFh[q?(F5FFFdr-F[uF[[qF>C%>F]q-Fbu6$F5Fjr>F^q-Ff`mFa^q@%2
FdsF^q>&FjrF^im&F[qF_bmC%>Fcfl-Fjq6$F]qFL>F^q-Feq6$Q"[F$Fcfl@%Fafq>Fcfq-F`r6$Fc
fl;Fdr,&F^qFdrFhtFdr>FcfqFcfl>&FirF_bmFjr>F=Fghm>Fir-Fbu6#-Fbu6#Fir?(F=FdrFdr-F
[uF[hqF>>Fegq-F[_l6#Fegq>FgdqFir>F]w-Fbu6#Fdbn?(F2FdrFdr-F[uFf\mF>>Fgdq-F[_l6#F
gdqOF]wF$F$F$6#Fdr%*get_HyposGt+F$F$F$F$O7$-Fbu6#%&FactsG-Fbu6#%&FuncsGF$6$Fbiq
%*FunctionsGF$6#Fds%,Has_ElementGt+6#%#exG6#F`sF$F$C$?&F2F:F>@$-%+Is_ElementGF
\uOF>OF%F$F$F$6#Fdr%*CheckNewsGt+6$F`dmFfbq6-Fd]l%&factsG%+factIndetsG%+ruleInd
etsGF+%#vsGF\^nF`s%&vars1G%)newFactsG%&nFactGF$F$C(>FjrF3>F5-F`bn6$-%)MyIndetsG
Ff^n<#Fds>Fip-F`bn6$-Fg[r6#&&F;FadqF_uFh[r@%/&F_\rF`vF3C$>Fjp-%/EquivalentObjsG
6$&F;F_uF:>Fjr-Fh_o6$FjpF^\rC%>Fjp-Ff\r6$Fb\rF:@$/FjpF3OFio@%2-F[uF^im-F[uFajmC
&>F[q-F`bn6$-Fg[r6#FbanF5>F\q-F`bn6$-F`bn6$<#-Fbu6#Fh\r-Fg[r6#Fb\rFh[r>F\q&F\qF
`v?&F]qF[qF>C%>F^q-FA6$Fjp<#/F\qF]q>F2-Fh_o6$F^qF^\r>Fjr-FA6$FjrF2C$>F2Fj\r>Fjr
Fd_r>Fcfl7$F:FjrOFcflF$F$F$6#FF%+MyCombinatGt+6$'%&doisoGF]fm%%FactG6*%'TH_ObjG
F\inF`s%&ToHopGFY%&OtempGF`dm%-TestCombinatGF$F$C*>F]qt+6$%#thG%&tohopGFcgoF$F$
C$?(F2FdrFdrF`amF>@$3-%(SubListG6$&F;F\uF:-Fcar6$F:FearOF>OF%F$F$F$6#FF>F=Fb]p>
F[qFio?&F\qF;F>@$-Fbhm6$-Fe_o6$F\qFdrF:>F[q7$FgjmF\q>F2-&%)combinatG6#%(permute
G6$F[qF=>FipFio?(F5FdrFdrFjtF>C$@$3/9#Fggm-F]q6$F]imFipF\^m@$/F:-%0Find_Fact_Ty
pesG6$F]imFdr>Fip7$F`eoF]imOFipF$F$F$6#FF%+xuly_GoalsGt+6#%'LGoalsG6(F[inF\jq%(
ex_varsGFYF`s%'updateGF$F$C(>F[qt+6#Fcdr6%F+F`sFaemF$F$C$>F2-F`bn6$F:-FA6$-FA6$
-Fjq6$Fban%$setG-Fjq6$%'OAttrsGFder-Fjq6$FeiqFder?&F=F2F>@)-%,Is_FunctionGF_bmC
&@$/-Fe_oF_bmQ&type?F$F\^m>Feiq7$FciqF=>%+Func_TypesG7$-Fbu6#FffrFafr?&F57#Fabm
F>-Fdo6#-Fb[pF^im3-%5ValidStructName_OnetGF_bm-Fgdm6$<#FabmFbanC%@$F`frF\^m>%*O
bj_TypesG7$-Fbu6#FhgrFafr>Fban7$-FbuF\^rF=3333-Fjim6$F=%)functionG/-Fbu6$FdsF=F
d`o4-Fgdm6$-Fbu6$FdrF=Fban-Fagr6#F\ir-Fgdm6$<#-FbuF_irFbanC'@$F`frF\^m>Fhgr7$Fj
gr-Fe_oF_ir>Fban7$F^hrF\ir>Fger7$-Fbu6#FgerF=>%,OAttr_TypesG7$-Fbu6#F`jrFafrC%@
$F`frF\^m>FgerF\jr>F`jrFajrF$F$6$FddrF[q6#Fdr>F2Fio?&FjpF:F>>F27$FdvFjp>F5F3?&F
=F2F>C$>Fip-%*Kind_FactGF_bm@$531FdrFip1Fip"#63-Fbhm6$F=%'ParamsG4-Fgdm6$F=%&Go
alsGC$>Fa\s7$-Fbu6#Fa\sF=>F5-FA6$F5Fe^q-F[qF^imF$6)Fa\sFeiqFffrFbanFhgrFgerF`jr
F$6#Fdr%.IsEqual_UnifyGt+6$F`em%&expr2GF$F$F$F$F$F$F$6#FFF^dnt+6$Fgbm%"bG6#F\am
F$F$C(>F2-Fh_oF9@$-Fecp6$F:%%DoanGOF2@$/F2F;C%@$/Fh^nFdsOF2>F2/Fh^nFd^n>F2-Fh_o
Feam@$F_^s>F2-%(algsubsGF9@$F_^sC%@$Fb^sOF2>F2Fe^s>F2-F[_sFeamOF2F$F$F$6#FF%-So
lveVecto_3Gt+F_ap61Ff]nFg]nFaap%*DoanVectoG%'listDVG%*kindFactsG%'btChenGFc]l%'
Facts3GFeap%,KiemTraChenGF`s%#btG%'btgiaiGF`]sF$F$C;>F]qF:>Fj^nF[_n>F]_nF3>F__n
F3>FdemF>>Fb_nFio>Fd_nFio>Fipt+F^em6'%'setVarGF\amF`sF_sF`emF$F$C(>F=Fio>Fjp-Fd
oFf^n>Fjp7$-FbuFe]qF_bo>Fjp-Fh_o6$/F\^sF`cmFjp?&F5FjpF>@$/-Fecp6$F5F`cmF>>F=7$F
abm-Fh_o6$7$/-Fe^nF^im*$FbbsFF/-F[_lF^im*$FebsFFF5OF=F$F$6$FeapFcfl6#Fdr>Fcflt+
F^em6%F]ipF^ipF`sF$F$C'>F=Fio>F2Fa[p?&F5F2F>>F=7$Fabm/F5-Fj[pF^im@$F\jpOF^jpOF:
F$F$F$6#Fdr>Fjrt+6$Fa_qFc]l6&F]ipF^ipF`sF_sF$F$C&>F=Fio>F2-Fb[pFe]s?&F5F2F>C$>F
ip-F]`q6$^#FdrF:@$/-F[u6#-F`bn6$-Fb[pFajmFd[pFdsO7$*$F5FF*$FipFFOF3F$F$F$6#FF>F
5t+6#Fj`m6'Fcdp%%chenGFd]lF_s%%exp1GF$F$C%>F2F>>FjpF:?(F$FdrFdrF$/F2F>?&F5F]^nF
>?&Fdo&F5F_uF>C%@$-Fbhm6$7$-Fbu6#&F5F`vFdoFd_nF\^m>Fip-F^dn6$FdoFjp@$/-Ffdn6$Fj
pFipF%C(>FdemF>>FjpFip>Fb_n7$F^`n7%7$7#Fgfs7#Fdo7#F\^qFjp>Fd_n<$FdenFffs>F=-Fa_
q6#Fjbm@$F\jpC%>Fip-Fgo6$FjpF=@$2FdsFf]rOFip>F=FioF$F$6&F`sF]wF]`sFjr6#Fdr@%2Fd
s-F[u6#&%*findKindsGFfgm>F^q-Fip6#&%*factKindsGFfgmC$>Fb_n7%FeoQ8Khong~the~giai
~bai~toanF$FeoOFb_n>Fb_nFio?(F$FdrFdrF$F^anF_an?&F]wFbanF>@$0-FfanFf\mFhan>F__n
-FA6$F__n-F]bnFf\m>F]^nF_bn>F]^nF_\q>FdemF>>F[cnFds>Fir-Fjr6$F]qFa^n@$2FdsF]hqC
(>Fb_n7$7%Fbfm7#-Fjq6$&FirF`vFLFe[t7%Fbfm7#-Fjq6$&FirF_uFLFj[t>F`o-%'expandG6#F
j[t>F]q-F86$F`oF:>F`q/F:-Fh_o6$FbiqF]q>Fb_n7&F^`n7%Fbfm7#-Fjq6$F`oFLF`o7%Fbfm7#
FgfqF]q7%Fbfm7#-Fjq6$F`qFLF`qOFb_n>Fir-F5F[an@$F][tC(>Fb_nF`[t>F`oF\\t>F]qF`\t>
F`qFc\t>Fb_nFg\tOFb_n>Fb_n7%FdfnF:F:OFb_nF$F`bqF$6#Fdr%,Minus_UnifyGt+F\dmF$F$F
$O-F`bn6$F:-FjcmF9F$F$F$6#FF%,Union_UnifyGt+F\dmF$F$F$O-FA6$F:-Fa^t6$F;F:F$F$F$
6#FF%+Get_ValuesGt+6#%&biensG6(%*get_valueG%*giatridonG%-cacgiatridonG%+tachgia
triG%%bienG%'valuesGF$F$C(>F2t+6#Fi_t6%F`dmI&valueG6$FivFjvFaemF$F$C)>F=F3@$-Fg
dm6$F:7$-Fbu6#&FafoF_u-Fbu6#&Fafo6#""(>F=-FA6$F=<#Q#xdF$?&F27$-Fbu6#&FafoFfgm-F
bu6#&Fafo6#"")F>@$-%+Unify_FactG6$-%)AttrNameGFf^n-Fe^nF\u>F=-FA6$F=<#-F[_lF\u?
&F27#-Fbu6#&Fafo6#""*F>@$-Fgdm6$F:Fibt@$-Fbhm6$Fdat-F`_t6#7#Febt>F=-FA6$F=<#Feb
t@$3-Fbhm6$Fd_oFhgr/F=Fcat?(F5FdrFdr-F[uFi`tF>@$334-Fiin6#/F:&Fj`tF^im-%,Is_Dac
TrungG6$<#F]etF:/-Fe_o6#F]etQ(PTDT_TQF$>F=-FA6$F=<#-FdoFdet@$31FFF^bm-Fbhm6$Fda
tF=>F=-F`bnFbat@'/F^bmFdsOQ$cxdF$F]bmOFabmOF=F$F$6$Fe_tF26#Fdr>F=t+6#%'giatriGF
]jqF$F$C$?(F2FdrFdrFb]pF>@$-Fjim6$&F:F\uFderOF2OFdsF$F$F$6#Fdr>F5t+F\gt6#%#gtGF
$F$C$?&F2F:F>@$0-FdoF\uFdsOF%OF>F$F$6$Ff_tF=6#Fdr>Fipt+F\gt6(FYF`sF_s%%seq1G%%s
eq2G%+giatritempGF$F$C%>F[qF:?(F$FdrFdrF$4-FdoFhjm?(F=FdrFdrFh_qF>C$>F2-Fgo6#Fd
fq@$FahnC'>Fip-F]`o6$&FdfqFcgo/Faem;Fdr,&F2FdrFhtFdr>Fjp-F]`o6$Fiit/Faem;,&F2Fd
rFdrFdr-F[uFcit>F5-Fe\o6$f*Fh\oF$Fi\oF$7%FdoF:FgoF$F$6&FghtFipFhhtFjp&FdfqF\u>F
[q-Fh_o6$/FdfqF_^pF[qFc[nOF[qF$F$6&Fg_tF5Ff_tF=6#Fdr@%-FjimF\fmC%>F[qFio?&FjpF:
F>>F[q7$Fgjm-F2Fe]q@$0-F=FhjmFds>F[q<#-Fbu6#-Fip6#7#F[q>F[q-F2Ff^nOF[qF$6$FafoF
hgrF$6#Fdr%,ApplyRuleBTGt+F^em6*FdemFd]lF`sFcemFd_nF_sF`^nFf]nF$F$C(>F]qF:>FipF
io>FjpFio>F2F>?(F$FdrFdrF$F^fsC$>F2F%?&F=F]^nF>?&F5FjfoF>C&@$-Fbhm6$7$-Fbu6#Fef
oF5FjpF\^m>F[q-Fh_o6$F5F]q>F\q-%*NhanVectoGFhjm@$/-Ffdn6$F]qF\qF%C'>F]qF^^u>Fjp
7$FbasFj]u>F2F>@%/-Fc[s6#-Fbu6$FdrFefoFF>Fip7$F`eo7$7#7$FeoF5F]q>Fip7$F`eo7$7#F
j]uF]q@$5Fjfn/-FdbmF[anF>OFipOFipF$Fa\qF$6#Fdr%#&+Gt+Fc]s6#%"cGF$F$C*@$50-FfanF
f^nF[^q0-FfanFaamF[^qO,&F:FdrF;Fdr@$50FacqF^ao0-FbcqFaamF^aoOF^au@$F^cmOF;@$/F;
F_cmOF:@$FbcmOF;@$/-Fbu6$FdrF;-Fbu6$FFF;OF:@&/FecmF^buC%>F2&F`cm6$FccmF`bu@$/-F
bu6$FdrF2-Fbu6$FFF2>F2F_cmOF2/F`buFccmC%>F2&F`cm6$F^buFecm@$Fjbu>F2F_cmOF2OF^au
F$F$F$6#FF%+get_ParamsGt+F$F$F$F$O7#-Fbu6#F]\sF$F`duF$6#FdsFgdmt+6$F`dmFbiq6$F`
s%&fact1GF$F$@%-Fjim6$F:FderC$?&F=F:F>@$4-Fgdm6$F=F;OF%OF>C$?(F2FdrFdrF`amF>@$-
FabtFgarOF>OF%F$F$F$6#FF%1Check_Facts_RuleGt+6$FjjqFfbq6*%&rTypeG%&fTypeGF+%(ne
wFactG%(fIndetsG%(rIndetsG%'facts1GF`sF$F$C%>F\qF:@%Fa\rC)>F2-Fbu6$FggmF;>F=Fio
?&F]qF:F>>F=7$Fabm-Fe_oF[an@$0F2F=OFio>F[qFj[r@$0Fb]pFh_qOFio>Fip-FfjqF9C*>F2-F
bu6#-Fbbq6#<#F;>F=-%*Rela_TypeGFf^n@$F_guOFio@$/&F;F`vQ"3F$>F\q-%)RoteFactGFf^n
>Fjp-Fg[rFegm>F[qFe^r@$0-F[uFe]qFh_qOFio>Fip-Ffjq6$F\qF;OFipF$F$F$6#FF%.Find_Va
rUnifyGt+F[jq6)F`sFaem%&flag1GF+F^[rF^_o%%usedGF$F$C*>F[qF3>FjpF3>FipFa[p>F\qF3
?&F2FipF>@$5-Fjim6$F2F^ao33-Fjim6$F2Fehr/-Fbu6$FdsF2Fd`o-Fjim6$F]cuF^aoC$>Fjp<$
FbasF2>Fip-F`bn6$FipFiam>Fjp7$F`eoFbas?&F2FjpF>C%>F5F%?&F=F\qF>@$-Fabt6$F2F=C$>
F[q<$Fgjm/F2F=>F5F>@$4F5>F\q<$F`\nF2OF[qF$F$F$6#Fdr%)ReplaceRGt+6$'%%combGF]fmF
fbqF$F$F$O-Fh_o6$-F]`o6$/&Fh\rF]jq&F:F]jq/F`s;FdrFb]pF;F$F$F$6#FFFb^ut+Ffes6$F`
emF_sF$F$C&>F2-F]\tFf^n@$0-F[u6#7#-&I,StringToolsG6$FivFjv6#_Fd^v%*SearchAllG6$
F[^qFefmFFOF:@$/-Fjim6$F2F\jmF>C%>F=Fa[p@$/-Fbhm6$F_cmF=F>OFds@$/-F[u6#-Fg[rF_b
mFFO,$-Fh_o6$/Fjfo-Fj[pFifoF2FhtOF:F$F$F$6#Fdr%7readDefineFunctionsTXTGf*FI63FW
FX%0readFuncStruct1G%-readFuncNameG%8readFuncArgumentAndTypeG%/readFuncReturnG%
-readFuncProcG%3readFuncPropertiesGFZ%)funcNameG%4funcArgumentAndTypeG%+funcRet
urnG%)funcProcG%/funcPropertiesGFY%(argTempGF_]pF$F$C1>F_wFds>F^qf*F$F$F$F$C'>F
doFeo>FgoFho>F[pFio>F]pFeo>F_pFioF$F$6,F\avFcflF]avFjrF^avF]wF_avFirF`avF`o>F[q
f*F$6$%%nameGFjimF$F$C&>FdoFdq>F=F_r>F2-F]r6#-F`r6$Fgo;,&-Feq6$Q'returnF$FgoFdr
Fe_lFdrFgel>F[p7$F2F=F$F$6(FYF`qFWF2F^avF]w>Fipf*F$F$F$F$C%>FdoFdq>F[pF_r>F]p-F
`r6$F[p;-Feq6$Fb\oF[p-Feq6$Ff]oF[pF$F$6*FYF`qFWF2F\avFcflFaavF\s>Fjpf*F$6$%*arg
Names1GF`sF$F$C&>FdoFdq>F2Fael?(F=FdrFdrFjtF>>F^u7$FauFiq>F_vFavF$F$6(FYF`qFWF2
F]avFjr>F\qf*F$F$F$F$C%>FdoFcw?(F$FdrFdrF$3Fcs/-Feq6$Q)end_procF$FdoFdsC$>F[p-F
geo6$F[pFdo>FdoFcw>F[p-Fgeo6&Q%procF$F]pF[pQ%end:F$F$F$6*FWF2FXF=F_avFirFaavF\s
>F]qf*F$Fh\oF$F$C$>FdoFcw?(F$FdrFdrF$Fe\lC%>F2F\[l@$-Fiin6#0F2%%NULLG>F[p7$FjzF
2>FdoFcwF$F$6(FWF2FXF=F`avF`o>F5f*F$F$F$F$C'Fgfl>FgoF]^l?(F$FdrFdrF$3F`^l/-Feq6
$Q/begin_functionF$FgoFdsC$>FgoF]^l@$2Fds-Feq6$Fd[mFgoOF$?(F$FdrFdrF$3F`^l/-Feq
6$Q-end_functionF$FgoFdsC$@+2FdsFggvFdhl2FdsF[cvFihl2Fds-Feq6$Q+begin_procF$Fgo
F^il2Fds-Feq6$Q+propertiesF$FgoFcil@$Fg^lFeil>FgoF]^l>%-Func_StructsG7$-Fbu6#Ff
iv7'FgpF\jlF]jlF^jlF_jlF$F$6<FZF^qFWF2FXF=Fg`vFipFi`vF[qFj`vF\qF[avF]qFh`vFjpF
\avFcflF]avFjrF^avF]wF_avFirF`avF`o>F=F]\m>F2F^hn>FfivFio?(F$FdrFdrF$F`hn>F2F^h
n?(F$FdrFdrF$3Fahn/-Feq6$Q-end_funtionsF$F2FdsFh`lFf^oOFfivF$FiivF$%+StructName
Gt+F[jqF$F$F$C%@$43-Fjim6$F:Fehr/-Fbu6$FdsF:Fd`oOF:@$-Fbhm6%F:&&-Fh^o6#FccmFfgm
F`v.FYO-Fd`o6$Fccm-F]r6#&&Fh[wF_u6#FYOF:F$F$F$6#Fdr%0Is_RelationTypeGt+6#'%&sli
stGF]fm6$%&nlistGF`sF$F$C%>F2-Fe\o6$f*Fh\oF$Fi\oF$Fj`uF$F$F$F:?(F=FdrFdr-F[u6#%
-Rela_StructsGF>C$@$/F2&&Fe]wF_bmF`vOF>@$33/&Fi]wF`vF\bo-Fbhm6$Q)doi_xungF$&Fj]
wF_u-Fiin6#/-Fjq6$F2Fder-Fjq6$Fi]wFderOF>OF%F$F$F$6#Fdr%/readObjectsTXTGf*FI6$F
XFWF$F$C*>%,Obj_StructsGFio>F2F]\m>F=F`_p?(F$FdrFdrF$3Fc_p/-Feq6$Q.begin_Object
sF$F=Fds>F=F`_p>F=F`_p?(F$FdrFdrF$3Fc_p/-Feq6$Q,end_ObjectsF$F=FdsC$@$Fb`p>Fd_w
7$-Fbu6#Fd_w7$-Fjq6$Fi`pFLFio>F=F`_pF[apOFd_wF$Fj`wF$F]frt+F[jq6%FY%"tGF`sF$F$C
&>F=Fefm>F2-Feq6$Fb\oF=@$3F^[wFahnC%@$-Fcar6$F^boFbanOF>?&F5F^boF>@$5-F]frF^im3
-FagrF^im-Fcar6$7#F_^pFbanOF>OF%OF%F$F$F$6#FdrFhcrt+6$FbiqF]cp6$F`dm%&TypesGF$F
$C%>F=Fio?&F2F:F>@%/FbcrFF>F=7$Fabm-Fe_o6$F2Fdr>F=7$Fabm-Fe_oF\uOF=F$F$F$6#FF%)
ChenDiemGt+6$Fgbm%"MG6)Fe`uF[_o%"eGFd]l%(diemDauG%)diemCuoiGF\amF$F$C.>FjpFccm>
F[qFecm>F2-Fh_o6$/F[qF;F:@$Fjbu>F2Fds>F=-Fh_o6$/FjpF;F:@$/F\ir-Fbu6$FFF=>F=Fds>
F5F`ew@$/-Fbu6$FdrF5-Fbu6$FFF5>F5Fds>Fip-Fh_o6$7$/F[qFjpFbewF:@$/-Fbu6$FdrFip-F
bu6$FFFip>FipFds>F\q7$,&F2FdrF=Fdr,&F5FdrFipFhtOF\qF$F$F$6#FF%-SolveVecto_2Gt+F
_apF$F$F$C$@%/-%-BieuThucNhanGFf^nF>-%-SolveVecto_7GFf^n-%-SolveVecto_8GFf^nOFb
_nF$F_`nF$6#Fdr%-SolveVecto_6Gt+F_apF$F$F$@%/-Fhgw6#Fd^nF>-%-SolveVecto_4GFf^n-
F_]nFf^nF$F$F$6#Fdr%)ReadExerGt+6#'%$urlGFL6+FWFX%-read_objectsG%+read_factsG%+
read_funcsG%+read_goalsG%,read_paramsGFddr%+readKindExGF$F$C/>F]qt+FhdrFidrF$F$
C$>F2F\er?&F=F2F>@)F\frC&@$F`frF\^m>FeiqFdfr>FffrFgfr?&F5F[grF>F\grF_grC%@$F`fr
F\^m>FhgrFigr>FbanF]hrF_hrC'@$F`frF\^m>FhgrFgir>FbanFjir>FgerF\jr>F`jrFajrC%@$F
`frF\^m>FgerF\jr>F`jrFajrF$F$6$FddrF]q6#Fdr>F^qt+F$F$F$F$>%(Kind_ExG-F[_l6#F\[l
F$F$6$FWF26#Fds>F\qt+F$F$F$F$C$>FdoFcw?(F$FdrFdrF$3Fcs/-Feq6$Q/end_parametersF$
FdoFdsC$>F]\s-FA6$F]\s<#F\[l>FdoFcwF$F$6&FWF2FXF=6#Fds>F5t+F$6)FY%%ten1G%&kieu1
G%#n1GF`sF\inFgbpF$F$C(>FdoFcw?(F$FdrFdrF$3Fcs/-Feq6$Q,end_objectsF$FdoFdsC%>F2
F^t@$2FdsF2C'>F=7#-F]r6#-F`r6$FdoF[jt>FipF^bm>F5-Fjq6$-F]r6#-F`r6$Fdo;FbjtF\vFL
>Fban7$F^hrFabm>Fhgr7$Fjgr-%"$G6$F5Fip>FdoFcw>%(objectsGFio>%*obj_TypesGFio?&F[
qFhgrF>@%-Fbhm6$F[qFh_xF\^mC$>Ff_x7$-Fbu6#Ff_xFio>Fh_x7$-Fbu6#Fh_xF[q?(F\qFdrFd
r-F[uF[hrF>C$-Fbhm6%-Fbu6$F\qFhgrFh_x.Fjp>&Ff_xFe]q7$-Fbu6#F_ax-Fbu6$F\qFbanF$F
$Fi\x6#Fds>Fipt+F$6&FYF[inFcdrF\jqF$F$C&>FdoFcw>F5F3?(F$FdrFdrF$3Fcs/-Feq6$Q*en
d_factsF$FdoFdsC%>F=7#F\[l?&FipF=F>C$>F2-Fc[sFajm@$31FdrF21F2"#7C%>Fbiq<$F`iqFi
p>&FafoF\u7$-Fbu6#FbcxFip>F5-FA6$F5F]es>FdoFcw-F[pF^imF$F$6(FWF2FXF=FddrF]q6#Fd
s>Fjpt+F$FhaxF$F$C&>FdoFcw>F5F3?(F$FdrFdrF$F`[mC%>F=Fdbx?&FipF=F>C$>F2Fhbx@$3Fj
bx4-Fgdm6$FipFgiqC%>Fgiq<$-Fbu6#FgiqFip>FbcxFccx>F5Fgcx>FdoFcwFjcxF$F$F[dx6#Fds
>F[qt+F$6&F[inF\jqFcdrFYF$F$C&>FdoFcw>F5F3?(F$FdrFdrF$3Fcs/-Feq6$Q)end_goalF$Fd
oFdsC%>F2Fdbx?&F=F2F>C$>FipFb[s@$53Fg[s1FipF]cxFj[sC$>Fa\sFd\s>F5Fh\s>FdoFcwFjc
xF$F$F[dx6#Fds-%+Reset_OnetGF$>F=F]\m>F2F^hn?(F$FdrFdrF$3Fahn/-Feq6$Q/begin_exe
rciseF$F2Fds>F2F^hn?(F$FdrFdrF$3Fahn/-Feq6$Q-end_exerciseF$F2FdsC,>F2F^hn?(F$Fd
rFdrF$33Fahn/-Feq6$Q1begin_hypothesisF$F2FdsF]hxC$@$2Fds-Feq6$Q(kind_exF$F2-F^q
F$>F2F^hn@$2FdsF^hxC$Ff^oOF[gv>F2F^hn?(F$FdrFdrF$3Fahn/-Feq6$Q/end_hypothesisF$
F2FdsC$@*2Fds-Feq6$Q,parameters:F$F2-F\qF$2Fds-Feq6$Q)objects:F$F2Fh`l2Fds-Feq6
$Q'facts:F$F2-FipF$2Fds-Feq6$Q+functions:F$F2-FjpF$>F2F^hn>F[_n-FAFfiq>F2F^hn?(
F$FdrFdrF$3Fahn/-Feq6$Q,begin_goalsF$F2Fds>F2F^hn-F[qF$>F2F^hnFf^oF$61Fd[xF[_nF
a\sF]\sFf_xFh_xFbanFhgrFbiqFafoFgerF`jrFeiqFffrFgiqF$6#Fdr%,Is_RelationGt+Ffbm6
$FjimF`sF$F$C%>F2F_hu?&F=F2F>@$50-FbcqF_bmF]fm/-Ff\wF_bmF%OF%OF>F$F$F$6#Fdr%,ge
t_ObjectsGt+F$6$%"OGF`sF$F$C%>F2Fio?(F=FdrFdr-F[uF\^rF>>F27$Fdv-Fgeo6%-Fjq6$&Fb
anF_bmFLFgq&FhgrF_bmOF2F$6$FbanFhgrF$6#FdsFjgwt+F_ap6+Fc]lF`sFd]lF_sF`^n%'dache
nGFa^nFbemFbdpF$F$C5>F2F:>F[qF3>Fj^nF[_n>F]_nF3>F__nF3>FdemF>>Fb_nFio>Fd_nFio>F
jfmFio>F2F:?(F$FdrFdrF$F^anF_an?&F=FbanF>@$0-FfanF_bmFhan>F__n-FA6$F__n-F]bnF_b
m>F]^nF_bn>F]^nF_\q>F[cnFds>FdemF>@$/-Fecp6$F2F\^sF>C$>Fb_n7$F^`n7%Fbfm7#-Fjq6$
-Fh_o6$FfasF2FLFi`y>F2F^fn?(F$FdrFdrF$F^anC)>F[cnF_cn>FdemF%>F\q-Fa_qF\u@$3F[]n
/-F^\p6$<#F`\nF[qF%C%>Fip-F]`q6$-%)ChuyenVeGF\uF\q>Fip,&-Fe^nFajmFdr-F[_lFajmFh
t@$/-Ffdn6$F2FipF%C*>F[q<$FgjmF`\n>F2-F]\tFajm@$FjenC$>Fb_n7%F^`n7%Fbfm7$-Fjq6$
FipFLQ"0F$F27%FbfmFdfmFdsOFb_n>FdemF>>Fjfm7$F\[n-Fbu6#-Fjq6$FipF]fm>Fb_n7%F^`n7
%Fbfm7$Facy-Fjq6$F2FLF2-Fbu6#-%*MyFactor0GF\u>F2F^fn@$FjenOFb_n>Fip-F\emF\u@$Ff
hsC%>Fb_n7$F^`nF`eo>F2F^fn@$FjenOFb_n?&F5F]^nF>?&F=FafsF>C'@$-Fbhm6$7$FgfsF=Fd_
nF\^m>Fip-F^dnFa\p>F]q-F`jm6#Fjby@$FjfnC$>Fb_n7$F^`n7%7$FhgsF^hp7$FacyF]qF]qOFb
_n@$/-Ffdn6$F2F]qF%C)@%5-Fjim6$-Fbu6$FdrFifsFgfp-Fjim6$F`gyFjfp>F^qFeo>F^qFgfs>
FdemF>>FjfmFhcy>Fb_n7%F^`n7%7$F`enF^hpF]]tF]q-Fbu6#-FfdyF[an>F2F^fn>Fd_n<$FdenF
iey@$5Fjen/-%*Is_Vecto0GF\uF>OFb_nOFb_nF$6+FdemFj^nF]_nF__nFb_nF[cnFd_nF]^nFjfm
F$6#FdrFg[rt+Ffes6'F`sF\amF^`sF_sFaemF$F$C&>F=<#-F]`o6$-F]`o6$-%#ifG6%/FjpFfdsF
fdsF[gv/FjpF2/F2F:>F5-%'indetsGFf^n?&F2F5F>@%5-Fjim6$F2Fgfp/F2Ffds>F=FgamC$>Fip
<#Fdv>F=-FA6$F=FipOF=F$F$F$6#Fdr%+Has_ObjectGt+F[jqF]jqF$F$C$?&F2F:F>@$4-%*Is_O
bjectGF\uOF%OF>F$F$F$6#Fdr%(MySolveGt+F)6(F/F.F-FdemF`dmFc]lF$F$C'>F5F3>F27#F7>
F2-%,Xuly_RootOfGF\u?&F=F2F>C%>FipF>?&FjpF=F>C$>F[q-F[_lFe]q@$53Facr/-Fiin6#1-%
'SignofGFhjmFdsF>2Fds-Feq6$Q"IF$Fc\nC$>FipF%Fc[n@$Fip>F5<$F_^pF=OF5F$F$F$6#FFF]
byt+F^em6'F`emFf]nFg]nF`sF_sF$F$C)>F=7#Fds>F5F`^z@$51-F[u6#Fa[pFdr-Fjim6$F:F\jm
OFjbm@%-Fjim6$F:Fd]n>F2Fifn>F2F:@$/-FjimFjcpF%OF:@%/-%'KTTichGF\uF>?&FipF2F>C$>
Fjp7#-Fc^v6$F[^qFacy@%2FdrF_iu>F=7$FabmFip>F57$F_^p,$FipFhtC$>F2Fjgm?&FipF2F>@%
1Fdr-%'coeffsGFajm>F=F``z>F5Fb`zO/-Fjq6$F=F]\n-Fjq6$F5F]\nF$F$F$6#FdrFagxt+F$6$
Ff_xFh_xF$F$C2>Fd[xFeo>F]\sF3>F2Fio>F=Fio>FbanFio>FhgrFio>FgerFio>F`jrFio>FbiqF
3>Fafo7.FioFioFioFioFioFioFioFioFioFioFioFio>F[_nF3>Fa\sFio>Fb_nFio>FeiqFio>Fff
rFio>FgiqF3F$60Fd[xF[_nFa\sFbanFhgrFbiqFafoFgerF`jrFb_nF]\sFeiqFffrFgiqF$6#FdsF
`\zt+6#F/6&%#L1G%'taphopGF`dm%$LngGF$F$C'@$/F:Fio-%'RETURNG6#Fio>F=&F:F`v@$/-Fe
q6$Q'RootOfF$-Fjq6$F=FLFds-Fdcz6#7$F=-Fbu6#-F`\z6#&F:6#;FFFb]p?&F5F=F>@$2Fds-Fe
q6$F\dz-Fjq6$FebsFLC%>Fip7#-%*allvaluesG6#Febs@%30FipFio/-Feq6$F\dzFacyFds>F2-F
e\o6$f*Fh\oF$Fi\oF$-FA6$-F`bn6$Fdo<#Fgo<#/-Fe^nFgrF:F$F$6&F^czF=F`dmF5Fip>F2Fio
Fc[n-Fdcz6#-F`\z6#7$Fdv-Fbu6$;FF-F[u6#%(ListSetGFdgzF$F$F$6#FdrFe_ot+6$%(elemen
tGF]cp6'FYF`s%&OtypeG%&nameAG%#OSGF$F$C$@*-Fbhm6%F:Fban.F2O&FhgrF\uF][wC&>F5-Fe
_oFj[w@$/F5FbfrOFbfr>FipFecm@%-Fjim6$FipF^aoO-FfanFajmC$>FjpFi[w@$-Fbhm6%F:&&Fj
pFfgmF`vFahzO&&FfizF_uF\uF\aoOFj`u-F]frFf^n?&F=FggnF>@$3/Fjfo-Fjq6$Fa[wFL-Fiin6
#/&F=Ffgm7#-F]`o6$-Fe_o6$F]boFdrF`bo@%FdcwOFefoOF=OFbfrF$F$F$6#FFFhgwt+F^em6&F`
emF`sFaemF_sF$F$C'@%F[_z>F2Fifn>F2F:@$2Fdr-%'degreeGF\uOF>@$F\_v@%2FdrF_^vOF>OF
%?&F=F2F>C$>Fip7#-Fc^v6$F[^qF]dz@$2FdrFf]rOF>OF%F$F$F$6#FdrFc[st+6#F`dmF^sF$F$C
$@/Fc[u@&333/Fb]pFF5-Fbhm6$FgczFban3-Fagr6#Fgcz-Fcar6$7#-Fbu6#FeduFban-Fjim6$&F
:F_uFL-Fbhm6$-Ffan6#Fa^[lFhgrOFdr2FdrFb]pC%>F2F:?(F=FFFdrFb]pF>@+-Fbhm6%Fe^p7$F
^hrF]jrF[\w>Fdhm-Ffan6#&7$FjgrFbjrFc\w3-Fagr6#Fe^p-Fcar6$7#-FbuFf_[lFban>Fdhm-F
fanFf_[l-F]frFf_[l>Fdhm&-Fe_oFf_[lF`v3-Fjim6$Fe^pFehr/-Fbu6$FdsFe^pFd`o>Fdhm-Ff
an6#F``[l>FdhmFhan@$-Ff\wF\uOFe_l-FbjqFf^nOFF3F[_z-FbjqFdhw@)-Fbjq6#Fh^nOFbdq-F
]frFda[lOFact4-Fiiq6#-Fb[pFda[lOFggmO""&3F[_z5-Fiiq6#-Fb[pFdhwFia[lOF^b[lF[jzOF
_at3F[_z-F]frFdhw@'Ffa[lO"#5Fha[lOF^btOFi[sOF]cxOFdsF$6&FbanFhgrFgerF`jrF$6#Fdr
Fdbtt+F[jq6&F\hzF_s%%propG%"pGF$F$C(@$43F][w-Fjim6$FecmF^aoOF:>F2-%.CObjectStru
ctG6#-Fjq6$-Fbu6$FdsFecmFL@$-Fbhm6%-Fjq6$FecmFLFb\wF[\wO&Fg[wFc\w>F5-Fh_o6$-F]`
o6$/&FgaoF]jq&7#-Fbu6#FecmF]jq/F`s;Fdr-F[u6#Fce[l&F2Fd_l?&FipF5F>@$-Fjim6$FipFd
]nC%>F=Feo@&/F`byFecm>F=Faby/FabyFecm>F=F`by@$3Fb`p-Fbhm6%F]dzFb\wF[\wOFjd[lOF:
F$F$F$6#FdrFcart+6$%&list1G%&list2GF$F$F$C$@$-F^\p6$-FjqFhdu-Fjq6$F;FderOF>OF%F
$F$F$6#FFF]`qt+6$Fc]l%%DiemG6+%&Chen1G%&rExprGFeemF`s%)exprTempG%%testG%'lExpr2
G%%sSetGFfemF$F$C&>F=F[b[l>F2t+6$Fc]lFa_q6'F`sF`em%%eSetG%&lExprGF_sF$F$C'>FipF
a[p>F5Fio?&F2FipF>C%@$/-Fbhm6$F2FdoF>F\^m>Fjp&-F^dwFeamF`v@$5/-Fbhm6$-Fbu6$FdrF
jpFgoF>/-Fbhm6$-Fbu6$FFFjpFgoF>C%>F57$F_^p/F2Fjp@%F[j[l>Fdo7$F`_lF^j[l>FdoF[[\l
Fc[n@$/Fe]rFds?&F2FipF>C$@$Fci[lF\^m>F57$F_^p/F2Fgi[lO-Fh_o6$F5F:F$F$6&FfemF^qF
`h[lF=6#FF@%/FchwF%C(>F^qFio>F5F`am>FipFdr>FjpFd^n?(F$FdrFdrF$FbinC$>Fjp-F26$Fj
p&F;Fajm>FipF^jnOFjpC&>F]qFio>F\qFcb[l@%2Fds-F[uFda[l?&FipF\qF>>F]q7$F_[q/Fip&-
F^dw6$FipFehuF`v?&FipF\qF>>F]q7$F_[q/Fip&Fd]\lF_uO-Fh_o6$F]qF:OF:F$F$F$6#FF%*Ap
plyRuleGt+6$FfbqFj^n6$F`dm%(setfactGF$F$@%-Fgdm6$&&F:FadqF`vF;C%>F=F3?&F2&Fi^\l
F_uF>@$4Ffdm>F=Fidm-FdczF_bm-Fdcz6#F3F$F$F$6#FF%)Is_EqualGt+F_]s6%FdemF`sFaemF$
F$C'@$3Fc[u-Fjim6$F;F]fmC%@$0Fb]pF`amOF%?(F=FdrFdrFb]pF>@$4-Fe_\l6$Fe^p&F;F_bmO
F%OF>@$3Fgdu-FjimFgg[lC%?&F=F:F>C%>F2F%?&F5F;F>@$-Fe_\lF_\pC$>F2F>Fc[n@$4F2OF%?
&F=F;F>C%>F2F%?&F5F:F>@$Fba\lC$>F2F>Fc[n@$Ffa\lOF%OF>>F2-Fiin6#/F:F;@$33/F2F%4-
FjimFffmFjb\l@&3-Fjim6$F:%(polynomG-Fjim6$F;F`c\l>F2-Fiin6#/-%)simplifyG6#-F]\t
6#,&F:FdrF;FhtFds3F[_z-Fjim6$F;Fd]n>F2-Fiin6#/-Fhc\l6#-F]\t6#,&-%$absGFhfnFdr-F
jd\l6#,&-Fe^nFaamFdr-F[_lFaamFhtFhtFdsOF2F$F$F$6#FFFagrt+6#F`bv6#%$Sn1GF$F$C'@$
4F\aoOF%@$4-Fbhm6$Fj`u-Fe\o6$f*Fc^pF$Fi\oF$FgczF$F$F$Fd_wOF%>F2-F]r6#&-Fb_o6#Fj
`uF`v@$54Fcju0Fb]pFjtOF%OF>F$F$F$6#FdrFc[zt+F[jqF]jqF$F$C$?&F2Fd_wF>@$-Fiin6#/F
efmF\boOF>OF%F$F$F$6#Fdr%+xuly_HyposGt+6#%'LHyposG6&F`sFddr%*read_factG%*read_f
uncGF$F$C'>F=t+FhdrFidrF$F$C$>F2F\er?&F=F2F>@)F\frC&@$F`frF\^m>FeiqFdfr>FffrFgf
r?&F5F[grF>F\grF_grC%@$F`frF\^m>FhgrFigr>FbanF]hrF_hrC'@$F`frF\^m>FhgrFgir>Fban
Fjir>FgerF\jr>F`jrFajrC%@$F`frF\^m>FgerF\jr>F`jrFajrF$F$6$FddrF=6#Fdr>F5t+F]jqF
haxF$F$C&>F5F3>F=7#F:?&FipF=F>C$>F2Fhbx@$33F[cx1F2Fi[s4-Fgdm6$FipFbiqC%>FbiqF`c
x>FbcxFccx>F5Fgcx-FdoF^imF$F$Fji\l6#Fdr>Fipt+F]jqFhaxF$F$C&>F5F3>F=Faj\l?&FipF=
F>C$>F2Fhbx@$3Fgj\lFjdxC%>FgiqF_ex>FbcxFccx>F5FgcxF`[]lF$F$Fji\l6#Fdr>F[_n<#F_b
o?&F2F:F>@%4-F]frF\u-F5F\u-FipF\uF$6,FbiqFgiqFeiqFffrF[_nFafoFgerF`jrFbanFhgrF$
6#Fdr%$UrlGf*6#'%)urlInputGFLF$F$F$C$>F]iwF:OF]iwF$6#F]iwF$Fbjqt+F[jqF$F$F$C$@(
5-Fbhm6$F:Fban-Fbhm6$F:FgerOF>3F][w5-Fbhm6$FccmFban3-FagrFj[w-Fcar6$7#-FbuFj[wF
banOF>3-FagrFf^nF\bwOF>OF%F$F$F$6#Fdr%1readRelationsTXTGf*FI6&FXFW%%expsGFd^pF$
F$C+>Fe]wFio>FipFio>F2F]\m>F=F`_p?(F$FdrFdrF$3Fc_p/-Feq6$Q0begin_RelationsF$F=F
ds>F=F`_p>F=F`_p?(F$FdrFdrF$3Fc_p/-Feq6$Q.end_RelationsF$F=FdsC$@$Fb`pC$>F57#Fi
`p@$/Fe]rFFC%@%-Fiin6#/F`gyQ"=F$>Fip-Fe\o6$f*Fh\oF$Fi\oF$FefmF$F$F$Fifs>Fip-Fe
\o6$f*Fh\oF$Fi\oF$-Fjq6$F^doFLF$F$F$Fifs>FifsFip>Fe]w7$-FbuFd]wF5>F=F`_pF[apOFe
]wF$Fd]wF$Fi_nt+6#F`em6-F`sF_sFY%1TheBestSolutionsG%.ShowSolutionsGFc]lFb_n%%Co
ngGFdem%%GoalG%'kVectoGF$F$C4>F=Fio>F\qFio@$FjbmO7$Fds7#Fccy>Fipt+F_`n6&F-%&Tru
ngGF`s%-Bo_Dau_NgoacGF$F$C'>F2Fio>F=Fio>Fipt+6#F]fm6$F`sF_sF$F$C$>F=Fio?&F2F:F>
@%5/F2Fb\o/F2Ff]oF\^m>F=7$FabmF2F$F$F$6#Fdr?&F5F:F>C$@%5/F5F=/-FipF^imF=F\^m>F2
7$FdvF5>F=F5OF2F$F$F$6#Fdr>Fjpt+F_`n6&F`sFYF-%2BieuthucDangChuoiGF$F$C'>Fipt+Fj
c]l6&F`sF-F_sFYF$F$C(>F=Feo>F5F:>FipFe]r@%-Fjim6$F[fw%(numericG>F=-Fgeo6%F=-Fjq
6$F[fwFLQ"*F$>F=-Fgeo6$F=Fef]l?(F2FFFdrFipF>@)-Fjim6$-Fbu6$F2F5Faf]l@%5-Fiin6#/
-Fbu6$F\jtF5Ff]o-Fjim6$Ffg]lF^ao>F=-Fgeo6&F=Q"+F$-Fjq6$F_g]lFLFgf]l>F=-Fgeo6%F=
F^h]lFgf]l-Fiin6#/F_g]lFb\o@%-Fjim6$Ffg]lFaf]l>F=-Fgeo6$F=F_g]l>F=-Fgeo6%F=F]h]
lF^h]l555-Fjim6$F_g]lF^ao-Fjim6$F_g]lF\jm-Fjim6$F_g]lFgfp-Fjim6$F_g]l%"^G@'Fgh]
l>F=-Fgeo6$F=F^h]l-Fiin6#/Ffg]lFb\o>F=F]j]l>F=F]i]l>F=F]j]lOF=F$F$F$6#Fdr>F5Fio
>F=Fb]p?(F2FdrFdrF=F>>F57$F_^p-Fip6#FhcqOF5F$F$F$6#Fdr>F]qt+Fjc]l6/F`sFaemFYF\a
mF_]pF_sFcemFfem%'numVarG%(numVar1G%'memVarG%$minG%$maxGF$F$C*>F[qF:>F5Fh_q>F\q
Fho>F]qFio?(F2FdrFdrF5F>C%@$-FbhmFjfyF\^m?(F=FbjtFdrF5F>C)@$-Fbhm6$F=F]qF\^m>F^
qFio>FjrFio?&Fjp7$&F[qF\uFdfqF>@%3-Fjim6$FjpF\jm2Fds-%)numelemsG6#-%'selectG6%F
jim<#FbasFaf]lC%>FcflFc]^l>F^q7$Fc[qF`[n>Fjr7$-FbuF[[q-Fbu6#-F`bn6$Ff]^l<#Fc[qC
%>Fcfl<#Fdr>F^qFj]^l>Fjr7$F]^^lFjp@$30-Feq6$F[^q-Fjq6$F[dnFLFds0-Feq6$F[^q-Fjq6
$FccnFLFds@$/-Fbu6$FdrF[dn-Fbu6$FFFccnC$>Fjr7$FccnF[dn>F^q7$&F^qF_u&F^qF`v>Fip-
Fb`u6$F[dnFccn@&F\izC+>FirFdr>F]wFF@$2Fa`^lF``^lC$>FirFF>F]wFdr@'3/F``^lFa`^l/F
a`^lFdr>Fh^r7'-Fbu6#Fh^rFb\oF[dnFccnFf]o3F`a^l2FdrFa`^l>Fh^r7(Fda^lFa`^lFb\oF[d
nFccnFf]oC$@%/&F^qFf\mFdr>Fh^rFca^l>Fh^r7(Fda^lF]b^lFb\oF[dnFccnFf]o@%/,&&F^qF[
hqFdrF]b^lFhtFdr>Fh^r7$Fda^l&FjrF[hq>Fh^r7%Fda^lFcb^lFgb^l@&0FipF_cm@%/F]b^lFdb
^l>&F\qF_u7$-Fbu6#F_c^l*&F]b^lFdrFipFdr>F_c^l7%Fac^lFcc^l*&Fcb^lFdrFgb^lFdr1Fdr
Fcb^l>F_c^l7$Fac^lFfc^l>F]q7$F_[qF=>FdoF>>F=FdsFc[nFiimC(>Fh^r7'Fda^lFb\o*&F``^
lFdrFccnFdr*&Fa`^lFdrF[dnFdrFf]o>F_c^l7$Fac^lFip>F]qF[d^l>FdoF>>F=FdsFc[n@$Fc_p
C$>Fh^r7$Fda^lFj\^l>F_c^l7$Fac^lFj\^l@$/-F[uFbc^lFds>F_c^l7#F_cm@$/F`e^lFdr>Fdo
F%OF\qF$F$6$FdemF^q6#Fdr@%-Fjim6$F:F]\n>F[qF[fm>F[qFaj\l?&F2F[qF>C$@$/-Feq6$F[^
qFadyFdsC$>F=Fdd]lF\^m@%F]_v@'/F]cuF_cmF\^m/-Fbu6$FdrF]cu-Fbu6$FFF]cuF\^m@%32Fd
s-Fa]^l6#-Fd]^l6%FjimFfjyFaf]l2-FbuFbg^lFds>F=7$Fabm,$*&Ffg^lFdr-Fj[p6#-Fbu6#-F
`bn6$FfjyFcg^lFdrFht>F=Fdd]l@'/F2F_cmF\^mFjbuF\^m>F=Fdd]l>F5F^bm@$/F5Fds>F=7$Fa
bmF_cm>F^qF>>F\qFc\u>F\q7$F`\nF=@$F]bm>F^qF%?(F$FdrFdrF$/F^qF>C$>F^qF%>F\q7$F`
\n-Fbu6#-F]q6#-Fbu6$FdgmF\q>Fcfl-Fjq6$Fji^lF]\n>F\q-FipFegmO7$Fcfl-FjpFegmF$F$F
$6#FdrF]bnt+Fa`x6)FjjqF_sFbemFjbq%$numG%%set1GF`sF$F$C)>FipF:>F[qFio@'/Fj`uQ-Hi
nhBinhHanhF$>F=%,HBH_StructsG/Fj`uQ(TamGiacF$>F=%/TamGiac_StrucsGOF3>F5-F]rF\^u
>FjpFe]r?(F\qFdrFdrFjpF>>F[q7$Fgjm/-Fbu6$F\qF5-Fbu6$F\qFipO<#7$7#7#Fip-Fh_o6$F[
q&F=Fd_lF$F$F$6#FdrFabtt+6$Fedu%&fact2G6-%#k1G%#k2GF^[r%&vars2GF`sFaemFdc[lF_sF
cc[l%'TestDXG%(Func_DXGF$F$C)>Fcflt+F$6,%&type1G%&type2GF`]x%#n2GF`sFaemFYF`emF
`]sFdemF$F$C*@$0&FicoF`v&T&F`vOF%>F2Fico>F5-F[uFhco>F=F_^_l>Fip-F[u6#F_^_l?(Fjp
FFFdrF5F>@%-Fjim6$&F2Fe]qF^ao>F\__l-Fjq6$-Fbu6$FdsF\__lFL>F\__l-Fe_o6$F\__lFdr?
(FjpFFFdrFipF>@%-Fjim6$&F=Fe]qF^ao>Fi__l-Fjq6$-Fbu6$FdsFi__lFL>Fi__l-Fe_o6$Fi__
lFdr@'5-%)RelaPropG6$F2Q)doi~xungF$-Fe`_l6$F=Fg`_lC'>F]q-Fjq6$&Fico6#;FFF5Fder>
F^q-Fjq6$&F_^_l6#;FFFipFder?&FjpF]qF>C%>FcflF%?&F[qF^qF>@$-Fabt6$FjpF[q>FcflF>@
$/FcflF%OF%?&FjpF^qF>C%>FcflF%?&F[qF]qF>@$F\b_l>FcflF>@$F`b_lOF%OF>0F5FipOF%C$?
(FjpFFFdrF5F>@$4-Fabt6$&FicoFe]q&F_^_lFe]qOF%OF>F$F$6&FeduF:F\]_lF;6#Fds>Fjrt+F
$6(F`bvFg]_lFh]_l%)tinhchatG%%funcGFd]lF$F$C%@$/F_^_lFicoOF>@$33/-Fbu6$FdsF_^_l
-Fbu6$FdsFico/-F[u6#7#-FbuFg^_lF\do/<#F^e_l<#FgcoC'>F2-Fjq6$Ffd_lFL>F=-FhcrF\e_
l>F5-FhcrF]do@$3-FcarF_\p-Fcar6$F5F=?&Fjp%*Fun_NamesGF>@$33-Fiin6#/F2&FjpF_u-Fc
ar6$F=Ffiz-Fcar6$FfizF=Fc[n@$-Fbhm6$Fg`_l&FjpFadqOF>OF%F$F$6&F\]_lF;FeduF:6#Fds
>F2-Fc[sFf^n>F=-Fc[sFaam@$F_guOF%@6/F2Fdr@$3-Fabt6$FgczFehu-Fiin6#/Fa^[lFh\rOF>
/F2FF@(-Fe_\lF9OF>333F\ao-Fjim6$F;F^ao-Fe_\l6$Fa[w-Fbu6$FdsF;/Fb\]l<#-FbuFaamC%
>F^q&-Fb_o6#F`jzFd_l>F^q-Fh_o6$-F]`o6$/&7#-Fbu6#-F]r6#&Fgi_lF`vFe]q&F^boFe]q/Fj
pFaboF^q?&F\qF^qF>@$53-Fjim6$F\qFd]n3/7#-Fbu6#-Fe^nFegmF^bo/7#-Fbu6#-F[_lFegm7#
Fci_l3/Fe[`lF^bo/F`[`lFi[`lOF>3333F][w-Fjim6$F;Fehr/F_i_lFd`o-Fabt6$FccmF^bu5/F
cbt-FdbtFaam3-Fabt6$-Fbu6$FdrFcbt-Fbu6$FdrFi\`l/-Fbu6$FFFcbt-Fbu6$FFFi\`lOF>/F2
Fggm@*3-Fe_\l6$Fd^nF^e\l-Fe_\l6$Fh^nF_e\lOF>3-Fe_\l6$Fd^nF_e\l-Fe_\l6$Fh^nF^e\l
OF>3-FabtF[^`lF\^`lOF>3-FabtFa^`lF`^`lOF>/F2Fbdq@&3Ff^`l-FabtF]^`lOF>3Fi^`l-Fab
tFc^`lOF>/F2F^b[l@'-Fe_\l6$,*Fd^nFdrFh^nFhtF^e\lFdrF_e\lFhtFdsOF>-Fe_\l6$,*Fd^n
FdrFh^nFhtF^e\lFhtF_e\lFdrFdsOF>C'>F5Fa[p>FipFd[p>F]qF;?&FjpF5F>?&F[qFipF>@$F\b
_l>F]q-Fh_o6$FdfwF]q@$30F]qF;-Fabt6$F:F]qOF>/F2Fe_l@%Feb\lOF>O-FcflF$/F2F_atO-F
jrF$/F2F^btOFf^`l/F2Fact@%-Fiin6#0Fd^nF^e\lOF%OF^_`l31FactF2Fhj\l@$Fcb\lOF>OF%F
$F$F$6#FF%-Compute_FuncGt+6&F]d_lFi_tF]gt%$triG6)FbgnF_sFjgtF^_oF`s%'ketquaG%+t
inhgiatriGF$F$C+>F\qt+6$FjgtF\in6$F-%$gttGF$F$C%>F2F3@$-Fbhm6$FdatF:C$>F=-Fgo6#
Fgco@$0F=F[gvC%>F2<#/F=-Fh_o6$F[p-F]rFhy@$0&T,FfgmFio@%/F;Fbdq>F2-FA6$F2<$-Fbu6
#&F]p6#F^b[l/F=&&F]pFfgmF`vC%>%(ObjsNewG7$-Fbu6#Ffe`lFbe`l>%*OTypesNewG7$-Fbu6#
F[f`l&Fce`lF_u>%)FactsNewG7$-Fbu6#Faf`l/Fbe`lF=>F2-FA6$F2<#F`d`lOF2F$F$6,Fi_tF;
FbgnF2F^_oFipF_sF=F]d_lF:6#FF>FipF3?(FjpFdrFdrF`amF>>Fip-FA6$Fip<#/&&Fa^[lF`vFe
]q&F;Fe]q@$0&F:FfgmFio@%/FbcrFbdq>Fip-FA6$Fip<#/&Fig`lF`v9'C$>Fip-FA6$Fip<#/Fah
`l-Fgeo6$Fah`lF[cn>F[cnF_cn>F=-Fh_o6$FipF:>F2-F]r6#Fi^\l>F[qF3@%-Fjim6$9&Fder?&
F5Ffi`lF>>F[q-FA6$F[q<#-F\q6$F5Fbcr>F[q-F\q6$Ffi`lFbcrOF[qF$6&Ffe`lF[f`lFaf`lF[
cnF$6#Fbdq%*Xuly_PhucGt+6#F.F$F$F$F$F$F$F$6#Fdr%%TestGt+F\][l6'Fc]lFeduF^[rF+Fd
]lF$F$C(@$5FgduFc[u?&FjpF:F>@$/-Fhj`lFe]qF%-Fdcz6#F%@$4F[_z-Fdcz6#F>>FipFa[p@$0
Ff]rFFFf[al?&F=<$-Fbu6#&FafoFadq-Fbu6#&FafoF`e`lF>C$>F5Fe^q@$33Fj`]l-%)Unify_in
G6$FipF5/-Fg[z6$<$F=F:FipF3Fb[alFf[alF$F$F$6#Fdr%3Replace_StructNameGt+F[jq6$F+
F^_oF$F$C%>F2Fa[p>F=-Fe\o6$f*Fh\oF$Fi\oF$/F:FcbtF$F$F$F2OF^jpF$F$F$6#Fdr%/Class
ify_FactsGt+6#'FjjqF]fm6%F`sFY%$SetGF$F$C%>F5F3?&F2F:F>C$>F=-Fc[sF\u@$31FdrF=1F
=Fi[s@$4-Fgdm6$F2&FafoF_bmC&>F`_al7$-Fbu6#F`_alF2>Fj^n-FA6$Fj^nFiam>F5-FA6$F5Fi
am>FdemF>OF5F$6%FafoFdemFj^nF$6#Fdr%-xuly_ObjectsGt+6#%)SObjectsG6'F`sFY%$tenG%
%kieuGF\inF$F$?&F2F:F>C$>F=-Feq6$FgqF2@$2FdsF=C'>F57#-F]r6#-F`r6$F2;Fdr,&F=FdrF
htFdr>FjpFe]r>Fip-Fjq6$-F]r6#-F`r6$F2;FghmFa[oFL>Fban7$F^hrF_^p>Fhgr7$Fjgr-Fb_x
6$FipFjpF$Fa^yF$6#FdrFb[pt+F^em6$%"FGF`sF$F$@)5-Fjim6$F:%)constantGF[c\lFb_\l55
-Fjim6$F:F`bvF\aoF^[wO<#F:F][alC%>F2F3?&F=F:F>@$4-Fbhm6$F=<$Fd^p%"yG>F2-FA6$F2F
e^qOF2C$>F2-Fb[p6#Fb\]lOF2F$F$F$6#Fdr%/Determine_GoalGt+6#Fgb]l6+FZ%'ValuesGF]d
_l%+funcstructGFjjqFa^alF]cp%(founddsGFYF$F$C(>F2t+F$F$F$F$C%>Ffe`lFio>F[f`lFio
>Faf`lFioF$F$F$6#FdsFhjl@$/Fd[xQ+Chung_minhF$-F_hwFf^n@$/Fd[xQ-Tinh_gia_triF$-F
e_sFf^n@$/Fd[xQ(Rut_gonF$-FbgwFf^n@$/Fd[xQ*Phan_tichF$-F]apFf^nF$6*%&TestFGFb_n
Ffe`lF[f`lFaf`lFafoFj^n%%fdexGF$6#Fdr%.Replace_UnifyGt+F^emF$F$F$F$F$F$F$6#FdrF
d\qt+6$Fc]nF]^n6)%(fSetnewG%'uuTienG%'xapSepGFeemF_sF`sFaemF$F$C->F2F;>F5Fio@$F
b^sOF2>F2Fio>F=F[b[l>FipF`am?(F[qFdrFdrFipF>>F57$F_^p7$-F[u6#-%*intersectG6$-Fb
[p6#&&F;FhjmF_uFe^qF[q>FipFe]r?(F[qFdrFdrFipF>?(F\q,&F[qFdrFdrFdrFdrFipF>@$2&&F
5FhjmF`v&&F5FegmF`vC%>FjpF`ial>F`ialFbial>FbialFjp?&F[qF5F>>F27$Fdv&F;6#&F[qF_u
OF2F$F$F$6#FF%*SolveFactGt+6$F`dm'F+Fder6$Fc]lF_g[lF$F$C%@%FacrC$>F2-Fhc\l6#-%,
dongian_ptOGFf^n>F=-Fg[zFeam>F=7#-Fg[z6$F:-%(SetVarsG6$Fd^n%&nameOG@$F[bm-Fdcz6
#F[gv-FdczF\^uF$F$F$6#FF%-readRulesTXTGf*FIF$F$F$C%>%*readRulesGf*FI66FWFXFaalF
balFZFcalFdalFealFgnFfalFgalFhalFialFjalF[blFYF`s%,ruleStructsG%)readReadG%)rea
dTrueGF$F$C2>Fjpf*F$F$F$F$C(>FdoFeo>FgoFio>F[pFio>F]pFdbl>F_pFeo>FapFeoF$F$6.Ff
alFcflFgalFjrFialFirFjalF`oF[blF`qFd\blF`\l>Fipf*F$F$F$F$>FdoFj^lF$F$6&FfalFcfl
FWF2>F`[lf*F$F$F$F$>FdoFj^lF$F$6&Fd\blF`\lFWF2>F[qf*F$F$F$F$C$>FdoFcw?(F$FdrFdr
F$F`clC$@$-Fjim6$F\[lFder>F_vF\[l>FdoFcwF$F$6(FWF2FXF=FjalF`o>F\qf*F$F$F$F$C$>F
doFcw?(F$FdrFdrF$F^dlC$@$F_^bl>F^uF\[l>FdoFcwF$F$Fc^bl>F]qf*F$F$F$F$C$>FdoFdq>F
[pF\rF$F$6(FYF\sFWF2F[blF`q>F^qf*F$F$F$F$C&>FdoFdq>F[pFael?(F]pFdrFdrFielF>>F_p
F[fl>FapF_flF$F$6.FYF\sFWF2FhalF]wF`sF_wFialFirFgalFjr>F5f*F$F$F$F$C(Fgfl>FgoF]
^l?(F$FdrFdrF$FjflC$>FgoF]^l@$FbglOF$>FgoF]^l?(F$FdrFdrF$FiglC$@-F`hlFdhlFehlFi
hlFjhlF^ilF_ilFcil2Fds-Feq6$Q)readTrueF$FgoFeil@$Fg^l-FgpF$>FgoF]^l>%-Rule_Stru
ctsG7$-Fbu6#Faabl7(F\jlF]jlF^jlF_jlF`jlT?F$F$6@FZFjpFWF2FXF=FbalFipFcalF[qFdalF
\qFealF]qFc\blF`[lFgnF^qFfalFcflFgalFjrFialFirFjalF`oF[blF`qFd\blF`\l>F=F]\m>F2
F^hn>FaablFio?(F$FdrFdrF$3Fahn/-Feq6$F]`mF2Fds>F2F^hn>F2F^hn?(F$FdrFdrF$3Fahn/-
Feq6$FeglF2FdsFh`lFf^oOFaablF$F$F$>Faabl-F_\blFf^nFaablF$6$FaablF_\blF$F\hwt+F_
apFe]nF$F$C4>Fj^nF[_n>F]_nF3>F__nF3>FdemF>>Fd_nFio>Fb_nFio>F2F:>Fb_n7$F^`n7%Fbf
m&-Fi_nF\uF_u&FhcblF`v>F2F^fn@$5FjenFch^lOFb_n?(F$FdrFdrF$F^anF_an?&F^qFbanF>@$
Fdan>F__nFjan>F]wF_bn>F]wFcbn>FdemF>>F[cnFds?(F$FdrFdrF$F^anC%>F[cnF_cn>FdemF%?
&FjrF]wF>?&F^qFccnF>C&@$FfcnF\^m>F]qF]dn>F`qFadn@$FddnC'>FdemF>>F2Fadn>Fb_nF\en
>Fd_nFcen@$FgenOFb_nOFb_nF$F\gnF$6#FdrFj[pt+FfbmFd`uF$F$C$@'F^cm>F2F_cmF\ao@%Fb
cm>F2F_cm>F2&F`cm6$FecmFccm>F2,$F:FhtOF2F$F$F$6#FdrF`jmt+F^em6-F`emF`sFaem%&num
s2GFeemF_sFfemFbaw%#t2GFdemFa^alF$F$C)>F2F[fm>FjpFjt@$Fg^zC$?(F=FdrFdrFjpF>@$-F
jim6$FdhmF]\n>Fdhm&-Fi_n6#FdhmF`vO-Fb^u6#-Fh_o6$/F_cmFds-FjqF^_v?(F=FdrFdrFjpF>
C'@$2-F[u6#7#-Fc^v6$F[^q-Fjq6$FdhmFLFFF\^m>F[q-Fjq6$FdhmF]fm>FipFh_q?(F5FdrFdrF
ipF>@$-Fjim6$&F[qF^imF]\n>Fbibl&-Fi_n6#FbiblF`v>Fdhm-Fb^u6#-Fjq6$F[qF\jm>F2-Fh_
o6$F]hblFicp@$/Fh[[lFFC)>F[qFjgm>FjpFh_q>FjrFio>F\qFio?(F=FdrFdrFjpF>C%@$5/-Fbh
m6$F=F\qF>1-Fi[[lFcitFdrF\^m@$2Fdr-F[u6#7#-Fc^v6$F[^q-Fjq6$FdfqFLF\^m?(F5FghmFd
rFjpF>C'@$5/-Fbhm6$F5F\qF>1-Fi[[lFfiblFdrF\^m@$2Fdr-F[u6#7#-Fc^v6$F[^q-Fjq6$Fbi
blFLF\^m>F]q-Fbu6$Fdr-Fb[pFcit>F^q-Fbu6$Fdr-Fb[pFfibl@$/-Fbu6$FdrF]q-Fbu6$FFF^q
C%>Fjr7$F]^^l/F^qF]q>F\q7$F`\nF5Fc[n>F2-Fh_oFe_rOF2OF2F$F$F$6#Fdr%*get_GoalsGt+
F$F$F$F$OFa\sF$Ff\sF$6#FdsFf_zt+F^em6$F`emF`sF$F$C'@$Fd^zOF%@$Fg^z@%F]\[lOF>OF%
@%/F[_zF>>F2Fifn>F2F:?&F=F2F>@$2Fdr-F[u6#Fc\[lOF>OF%F$F$F$6#Fdr%*Test_GoalGt+6$
Fgb]lFbiqF$F$F$O-FgdmF9F$F$F$6#FFF`ant+F$6*%"rGF\fuF]fuFd]l%(factsOKG%)factsSet
GF\am%%newsGF$F$C'>F\qFio>FdemF%?&F2FaablF>@%0&&F2FadqF`vF3C&@%2Fds-Fa]^lFaiq>F
5-F`huFaiq>F5F3>F=-Fbbq6#7#F2>F=Fabm@$/F\f_lF>C&>FjpF3?&FipFbiqF>C$>F5-F`hu6#Fe
\_l@$/F]f_lF>>Fjp-FA6$Fjp<#Fip>F[q-Fgbr6$FjpF^bm?&FipF[qF>C&>F]q-FheuFdjo>Fbaw-
Fcar6$<#F]q-FA6$Fj^nF]_n@$0F]qFio>%#t1G-Fcar6$&F]qF_uFbiq@$33Ficcl/FbawF%/F[dcl
F%C$@%/-Fa\y6#F^dclF%@%/F\boFccy>F]_n-FA6$F]_nFeccl>Fj^n-FA6$Fj^nFeccl>Fbiq-FA6
$FbiqF^dcl>FdemF>@%/-Fcar6$Fb`oFhgrF>C&>FjpF3?&FipFbanF>@$/-Fbhm6$-Fe_oFajmFb`o
F>>FjpFhbcl>F[q-Fgbr6$Fjp-F[u6#Fb`o?&FipF[qF>C&>F]qFaccl>FbawFcccl>F[dclF\dcl@$
F`dclC$@%Ffdcl@%Fjdcl>F]_nF\ecl>Fj^nF_ecl>FbiqFbecl>FdemF>F\^m-%&printG6#Qhn---
----------------------------------------------------------F$?&FipFbiqF>C$@$/-Fe
cp6$FipF`cmF%F\^m@$/-FbcqFajmFd]nC+>F[dclF3>F]qF_by>F]q/FadnF_cm>F[dcl-FA6$F[dc
lFeccl>F]q,&F`byFhtFabyFdr>F]qFehcl>F[dclFghcl>Fj^n-FA6$Fj^n<#7$FcfmFjbcl>Fj^n-
FA6$Fj^n<#7$Fe\_lF[dclF$6,FbiqFaablFj^nFafoFdemFbawF[dclFb_nF]_nF__nF$6#Fds%.Ou
tput_ResultGt+Fjdal6'F\amF`sF_sFaem%#lsGF$F$C(-I*writelineG6$FivFjv6$FifalQQ###
#############################################F$@(FhealC$-F_jcl6'FifalQ'CMDT:~F$
FefmQ(Ta~co:~F$-Fjq6$/FifnFdsFL>FjpQ)=>~VT~=~F$F`falC$-F_jcl6%FifalQ'RGBT:~F$-F
jq6$/%#BTGF:FL>FjpQ*~=>~BT~=~F$FdfalC$-F_jcl6$FifalFhjcl>FjpQ%~=>~F$@$/-Fbu6$Fd
rFb_nFdfnC&-F_jcl6%Fifal-Fjq6$-Fbu6$FFFb_nFLQ"|+F$-F_jcl6$FifalQ$KGDF$-F_jcl6$F
ifal-Fjq6$-Fbu6$FggmFb_nFLOF$>FipFds?&F=Fb_nF>C$@&0-Fbu6#&FefoF`vFeo-F_jcl6'Fif
alQ%Vi:~F$-Fjq6$Fj]dlFLQ'~nen:~F$-Fjq6$&FefoF_uFL0-Fbu6#Fc^dlFeo-F_jcl6%FifalQ'
Ta~co~F$-Fjq6$&F=6$FdrFFFL?&FipFjfoF>-F_jcl6$Fifal-FgeoF`gs@$Fheal-F_jcl6$Fifal
-Fgeo6$Q#=>F$FefmF$6$Fb_nFifalF$6#Fdr%,xuly_ParamsGt+6#%(SParamsGF]jqF$F$?&F2F:
F>>F]\s-FA6$F]\s<#-F]rF\uF$F`duF$6#FdrFfdyt+Fbb]l6'Fdem%'rutgonGFcemFah[lFbemF$
F$C'>F=t+F^em61%)exprListG%*exprList1G%*exprList2GFfemF_sFbem%)tempListG%(numLi
stGF`sFaemFd]l%#f2G%&flagRG%&h_posG%&g_oalGF$F$C,>FipFio>F=Fio>F5Fio>F2F[fm>F]q
Fjt>FdoF%?(F^qFdrFdrF]qF>C(@$-Fbhm6$F^qFipF\^m>F\qFio>F`oF3>F`qF3?(Fcfl,&F^qFdr
FdrFdrFdrF]qF>C%@$-Fbhm6$FcflFipF\^m>Fjp-Faim6#,&&F2FganFdr&F2Fa[nFdr@%/-F`jmFe
]qFdsC&>F\q7$FjpFds>Fip7$F`eoFcfl>FdoF>Fc[n@$/-Fjim6$F]^nFgfpF%C$?&FjrF]^nF>C%>
FirF%?&F]wFccnF>C$>F[q-F^dn6$F]wFjp@$/Fi\nFdsC)>F\qFecdl>FipFgcdl>F`o<$F[dn-Fbu
Fg^q>F`q<$-Fbu6#F`qF]w>FirF>>FdoF>Fc[n@$/FirF>Fc[n@$FeedlFc[n@%FjdqC$>F=7$FabmF
h^r>F57$F_^pF_c^lC$>F=7$FabmF^cdl>F57$F_^pF^cdl@$/FdoF%OFio@$/-F[uFaedlFdsC$>F`
o<#Feo>F`qFjfdlO7$7%Fbfm7#-Fjq6$F_azFLFeo7%7$7#F]edl7#F`edl7#-Fjq6$FaazFLFaazF$
F$6$FdemF26#Fdr>F57#-Fbu6#-F=6#F\^v>F2F>@$2FdsFe]r?(F$FdrFdrF$F^fsC%>F2F%>Fip&&
F56#Fe]rFfgm>F57$F_^p-Fbu6#-F=6#F_sOF5F$6$F]^nFjfmF$6#FdrFf\rt+6$Fies%%exp2G6'F
`sF\am%#e1G%#e2GF_sF$F$C&>F=F3@$F_`\lOF3?(F2FdrFdrFb]pF>C%>F5Fhcq>FipFdam@%2Fdr
Fe]rC%>Fjp-Ff\rFc_x@$Fa]rOF3>F=-FAFgep>F=-FA6$F=<#/FhcqFdamOF=F$F$F$6#FFFfant+F
h\oFc\wF$F$C%@$F[c\lC$>F2-Feq6$F\gqF:@%F\^xO-F`r6$F:F[jtOF:@$F\aoOF`jzOFhanF$F$
F$6#Fdr%0Determine_ParamGt+6#%$ParG6,FjjqFjbq%$EqsG%)find_objG%*call_funcG%+fin
d_fact9G%-GetVars_PolyG%(set_eqsG%*test_goalGFZF$F$C.>Fipt+6#%$parG6$F`dm%%objs
GF$F$?&F2FiatF>@$-Fbhm6$F:-Fb[p6#FjbtC$@$/-Fe_o6#F[_lFeetO&-Fbu6#FebtF`vOFebtF$
F$F$6#Fdr>Fjpt+6#F]d_l6#%&fnameGF$F$C%>F2-%0Find_FuncStructGFc_o>F2-F]r6#F_aclO
-F26#-Fbu6#-F`_tFcboF$F$F$6#Fdr>F\qt+F^emFhbalF$F$@)F[calOF35F`cal3F^[w-Fiin6#/
Fa[wQ".F$OFdcalF][alC%>F2F3?&F=F:F>>F2-FA6$F2-FdoF_bmOF2C$>F2-FdoFedalOF2F$F$6$
F[]elF\q6#Fdr>F]qt+6$F[cq%#vpG6$Faem%$eqsGF$F$C$>F=F3@%0Fb]pFdrC$?(F2FdrFdrFb]p
F>@$0-Fdo6#/FcgtFearF3>F=-FA6$F=<#FbbelOF=O<#Feb\lF$F$F`ael6#FF>F[qt+6#%&otempG
6)%&fact9GF[cqFeaelFgael%$ansGFaemF\amF$F$?&F2F_ctF>@$-Fbhm6$F:<$Febt-FbuFj]elC
)>F=-F`_tFc^el>F5-FdoFj]el>Fip-FgoF_\p>Fjp-F[pFajm>Fb_n7$F^`n7&Q-Ap~dung~sk~9F$
FjaclFfcelFip@$/Ff]rF_iuC%>F\q-F8Febal>Fb_n7$F^`n7&Q(Giai~ptF$FioFipF\qOF\q>F]p
-FA6$F]pFipF$F$6*Fi\elFjpF\]elF]qF[]elF\qFg\elF56#Fdr>F^qt+6%Fb]elF^celF_s6%Fae
mFd]l%"oGF$F$C$?(F2FdrFdr-F[u6#Ffi`lF>@$/F:-Fe^n6#&Ffi`lF\uC'-%'printfG6#Q3Bai~
toan~giai~duocF$-Fdfel6$Q1|+Ket~qua~la~:~%aF$Fafel-Fdfel6$Q2|+Loi~giai~la:~|+%a
F$Fb_n?(F=FdrFdr-F[uFhatF>@$/F;-Fe^n6#&FiatF_bm>Fcgel-Fh_o6$FafelFcgelOF>OF%F$F
$F$6#Fggm>F=-FipFf^n>F5F3>Fb_nFio>F2-F[qF_bm@$-F^q6%F:F=F2OF$OF5F$6$FafoFb_nF$6
#Fdr%7readDefineOperatorsTXTGf*FI63FWFX%/readOpsStruct1G%,readOpsNameG%7readOps
ArgumentAndTypeG%.readOpsReturnG%,readOpsProcG%2readOpsPropertiesGFZ%(opsNameG%
3opsArgumentAndTypeG%*opsReturnG%(opsProcG%.opsPropertiesGFYFaavF_]pF$F$C1>F_wF
ds>F^qf*F$F$F$F$C'>FdoFeo>FgoFho>F[pFio>F]pFeo>F_pFioF$F$6,F`ielFcflFaielFjrFbi
elF]wFcielFirFdielF`o>F[qf*F$F_bvF$F$C&>FdoFdq>F=F_r>F2Febv>F[pF_cvF$F$6(FYF`qF
WF2FbielF]w>Fipf*F$F$F$F$C%>FdoFdq>F[pF_r>F]pFgcvF$F$6*FYF`qFWF2F`ielFcflFaavF
\s>Fjpf*F$FadvF$F$C&>FdoFdq>F2Fael?(F=FdrFdrFjtF>>F^uFhdv>F_vFavF$F$6(FYF`qFWF2
FaielFjr>F\qf*F$F$F$F$C%>FdoFcw?(F$FdrFdrF$F`evC$>F[pFgev>FdoFcw>F[pF[fvF$F$6*F
WF2FXF=FcielFirFaavF\s>F]qf*F$Fh\oF$F$C$>FdoFcw?(F$FdrFdrF$Fe\lC%>F2F\[l@$Fhfv>
F[pF]gv>FdoFcwF$F$6(FWF2FXF=FdielF`o>F5f*F$F$F$F$C'Fgfl>FgoF]^l?(F$FdrFdrF$3F`^
l/-Feq6$Q/begin_operatorF$FgoFdsC$>FgoF]^l@$2Fds-Feq6$Q.end_operatorsF$FgoOF$?(
F$FdrFdrF$3F`^l/-Feq6$Q-end_operatorF$FgoFdsC$@+2FdsFd]flFdhlFjhv-%.readopsRetu
rnGF$F[ivFihlF_ivF^il@$Fg^lFcil>FgoF]^l>%+Op_StructsG7$-Fbu6#F]_fl7'FepFgpF\jlF
]jlF^jlF$F$6:FZF^qFWF2FXF=F[ielFipF^ielF\qF_ielF]qF\ielFjpF`ielFcflFaielFjrFbie
lF]wFcielFirFdielF`o>F=F]\m>F2F^hn>F]_flFio?(F$FdrFdrF$3Fahn/-Feq6$Q0begin_oper
atorsF$F2Fds>F2F^hn?(F$FdrFdrF$3Fahn/-Feq6$F]^flF2FdsFh`lFf^oOF]_flF$F`_flF$F`h
ut+6#%&relasG6'F\amFd`cl%(op_typeGF`sFaemF$F$C(>F5-Fe_o6#F_bo@$30F5Fbfr/Fb]pFdr
O7#F5?(FjpFdrFdrFb]pF>C&>F=&F:Fe]q@$Fd_yC$>F\__lFe_yF\^m?(FipFFFdrF^bmF>C$>F5-F
e_o6#-Fbu6$FipF=>&F=FajmF5>F\__lF=>F2-Fbu6#Fdv?(FipFdrFdrFjtF>>&F2Fajm-F[_l6#Fh
bflOF2F$F$F$6#FdrF^_elt+Fh^elF]jqF$F$?&F2FfivF>@$3-Fiin6#/Fa^[l-Fjq6$-Fbu6$FdsF
jaoFL/Fig`l&F^epF_uOF2F$F$F$6#FdrFa_qt+F^em6/F`sFaemF\amFf]nFg]n%)listDiemGF`em
%)chonDiemG%'vitriNGF_sFbemFY%&indexGF$F$C%@$2Fe^zFFOFio@%/-&F"6#FhgwFf^nF>C(@$
3Fa_cl0Fh^nFdsC'>FjpFh[`l>FipFc[`l>Fcfl-F`bn6$-Fg[rFe]q-Fg[rFajm@$/-F[uFa[nFdsO
-F`bn6$FfeflFeeflOFcfl@%5/F[_zF%Fb^s>F\q-F]byFf^n>F\qF:>FjpFh[`l>FipFc[`l>F5Fio
@(30FjpFds0FipFdsC%>FcflFcefl@$FheflOF[fflOFcfl3Fjffl/FjpFdsC(@%FiimC$>FcflF]es
O-Fchal6$-Fg[r6#&FcflF`v-Fg[r6#&FcflF_u>FipF[dy>F[qFfefl>F]qFio?&F2F[qF>C%>F^q<
#Fjacl?&F=FipF>C&>FcflFe^q>FjrFio?&F]wFcflF>C$>Fir-Ff`m6$F2F]w@$2FdsFir>Fjr7%F]
^^lFirF]w@$2FdsFieq>F^q<$Fc[qFjr@$/,&-F[uFganFdrFhtFdrFf]r>F]q7$F_[qF^q?&F2F]qF
>C$>Fcfl<#-F]`o6$-Fbu6#-Fd]^l6%FjimF=%(integerG/F=F2@$/FieflFdr>F57$F_^pF]gpOF5
3/FipFdsFifflOFioC$@$F`fflOFio@$F^eflC+>FcflFio>FjrFio>FipFcb[l>FjpF[b[l>Fcfl7#
-F]`o6$-Fbu6#-Fg[rF\u/F2Fip>Fjr7#-F]`o6$F^\glFhj[l?(F2FdrFdrFieqF>?(F=FdrFdrFie
flF>@$/&FjrF\u&FcflF_bmC$>Fj\glFds>F[]glFdr>Fjr-%'removeG6%FecpFjrFdsOFjrOFioF$
F$F$6#FdrFZf*F$6#FKF$F$C,>F2-Fgeo6$F]iwQ2/data/Objects.txtF$-F__wF\u>F2-Fgeo6$F
]iwQ4/Data/relations.txtF$-F]_]lF\u>F2-Fgeo6$F]iwQ?/data/Objects/HinhBinhHanh.t
xtF$>F`[_l-FGF\u>F2-Fgeo6$F]iwQ:/data/Objects/TamGiac.txtF$>Fd[_lFh^gl>F2-Fgeo6
$F]iwQ0/data/Rules.txtF$-F[\blF\uF$6(Fd_wFe]wFaablFd[_lF`[_lF]iwF$Ffhwt+F_apFd^
yF$F$C8>F2F:>F[qF3>Fj^nF[_n>F]_nF3>F__nF3>FdemF>>Fb_nFio>Fd_nFio>FjfmFio>F2-F]
\tFhfn@$FjenC$>Fb_n7&FcfmFcfm7#FadyFdsOFb_n?(F$FdrFdrF$F^anF_an?&F=FbanF>@$Fd_y
>F__nFg_y>F]^nF_bn>F]^nF_\q>F[cnFds>FdemF>@$F_`yC$>Fb_nFd`y>F2F^fn?(F$FdrFdrF$F
^anC)>F[cnF_cn>FdemF%>F\qFaay@$FcayC%>FipFjay>FipF_by@$FcbyC*>F[qFhby>F2Fjby@$F
jenC$>Fb_nF^cyOFb_n>FdemF>>FjfmFhcy>Fb_nF^dy>F2F^fn@$FjenOFb_n>FipF[ey@$FfhsC%>
Fb_nF_ey>F2F^fn@$FjenOFb_n?&F5F]^nF>?&F=FafsF>C'@$FgeyF\^m>FipF[fy>F]qF]fy@$Fjf
nC$>Fb_nFbfyOFb_n@$FhfyC)@%F]gy>F^qFeo>F^qFgfs>FdemF>>FjfmFhcy>Fb_nFigy>F2F^fn>
Fd_nFahy@$FchyOFb_n>FipF^fn>Fb_n7%FdfnF[[dlF_[glOFb_nF$FihyF$6#FdrFihut+6#Fjjq6
,F`sFaemF`dmFhj^l%%set2GF_sFbemFYFadfl%*diemChungGF$F$C$@%F_aflC2>F5F_bo>F[qF]f
w>F\q-Fbu6$FggmF5>FipFio>FjpFio@%/-FfanFegmFb[_l>F]qFggm>F]qFbdq>Fcfl-Fchal6$-F
g[rFhjmF[iu>F^q,&-Ff`m6$F`[nF\qFdrFhtFdr>F=Fdr?&F2F\qF>C%>Fip7$F`eoF`\v@%1,&F=F
drF^qFhtFds>Fjp7$Fbas/,(F=FdrF^qFhtF]qFdrF2>Fjp7$Fbas/F_gglF2>F=Fghm>F\q-Fh_o6$
FipF\q>F\q-Fh_o6$FjpF\q@$/-Ff`m6$F`[nF[qFF>F[q&F\^s6$-Fbu6$FFF[q-Fbu6$FdrF[q>Fa
fsF[q>&F5FfgmF\qO<#F5C,>F5F[fm>Fcfl-Fchal6$-Fg[r6#&FgczFfgm-Fg[r6#&Fa^[lFfgm@$F
heflOF:>F2-Ff`m6$F`[n&FifsFfgm>F=-Ff`m6$F`[n&FafsFfgm>F[qF^jgl>F\qFbjgl@$Fdh_l>
F^jgl&F\^s6$-Fbu6$FFF^jgl-Fbu6$FdrF^jgl@$/F=FF>Fbjgl&F\^s6$-Fbu6$FFFbjgl-Fbu6$F
drFbjglO<#F_^pOF:F$F$F$6#FdrFb_of*6$'%(objNameGFLF[in6$F`sFdemF$F$C)-I%withG6$F
ivFjv6#Fd^v>F=Fds?(F2FdrFdr-F[uFj`wF>@$-Fiin6#/-%*UpperCaseG6#&&Fd_wF\uF`v-F\]h
lFf^nC$>F=FdrFc[n@$/F=FdsOF[gv@$3Fdcw/F;Q&resetF$C$>&F_]hlF_uFioOF[gv@$/F\^hlFi
o>F\^hl-FG6#-Fgeo6&F]iwQ//data/Objects/F$F:Q%.txtF$OF\^hlF$6$Fd_wF]iwF$Fe`_lt+6
$Fi\w'Fcc[lFLF[]wF$F$C%>F2-Fe\o6$f*Fh\oF$Fi\oF$Fj`uF$F$F$F:?(F=FdrFdrFc]wF>@$Fh
]w@'/FbcrFdrOFd^w-Fbhm6$F;Fd^wOF>OF%@%Fd_hlOF3OF%F$F$F$6#FF%0Determine_GoalsGt+
F$6&FZFgb]l%&time1G%)filenameGF$F$C,>Fip-Fgeo6$-I+currentdirG6$FivFjvF$Q-/baigi
ai.txtF$>Fifal-F^\m6%Fip%&WRITEGFb\m>F5-%%timeGF$>F2t+F$F$F$F$C%>Fj^nF[_n>Fd_nF
3>F[cnFdsF$F$F$6#FdsFhjl>%%SolsGFio>Fb_nFio?&F=Fa\sF>C%>Fb_nFio@%-F\`cl6$F=Fj^n
C$-Fdfel6#Q>(@_@)Bai~toan~khong~can~giai|+F$-FiiclF_bmC$-FhdalF_bmFfbhl@$0Fb_nF
io>Fjahl7$-Fbu6#FjahlFb_n-Fa`m6#Fifal-%'lprintG6$%+Total~TimeG,&F`ahlFdrF5FhtF$
63Fj^nFhfalFd_n%'TestORG%(TestOCRGFb_nFa\s%$DF3G%%DF43G%%DF53G%%DF45G%$DF9G%$DF
8G%)TestPropGF[cnFjahlFifalF$6#FdsF_ett+6$%#O1G%#O2G6$FfbqFd`clF$F$C$?&F2&-Fb_o
6#-Fe_oFaamF]btF>@$-Fiin6#/F\boQ3xac_dinh_doi_tuongF$C$>F=-Fe\o6$f*Fh\oF$Fi\oF$
-Fd`o6$FicoF:F$F$6$FddhlF;F^acl@$-Fiin6#/F:F=OF>OF%F$F$F$6#FF%1Replace_AttrName
Gt+F$F$F$F$F$F$F$F$6#FdsF$
